const Map<String, String> ar = {
  "forgetPassword": "نسيت كلمة السر",
  "forgetPassDesc":
      "فضلاً ادخل البريد الالكتروني الخاص بك حتى يصلك رمز التوثيق",
  "email": "البريد الالكتروني",
  "confirmEmail": "التحقق من البريد الالكتروني",
  "otpForgetDesc": "تم ارسال رمز التحقق الى البريد الالكتروني thra@thraco.sa",
  "passChanged": "تم تغيير كلمة السر بنجاح",
  "backToLogin": "العودة إلى تسجيل الدخول",
  "newPassword": "كلمة السر الجديدة",
  "password": "كلمة السر",
  "confirm": "تأكيد",
  "login": "تسجيل الدخول",
  "rememberMe": "تذكرني",
  "forget_password_question": "نسيت كلمة السر؟",
  "no Account": "ليس لديك حساب؟ سجل الآن",

  // Onboarding
  "onboarding1": "عوائد سنوية تصل حتى 17% سنويًا",
  "onboarding2": "فرص استثمارية متعددة",
  "onboarding3": "سجل واستثمر في المشاريع العقارية بخطوات سهلة وآمنة",
  "registerNow": "سجل الآن",
  "partner": "شريكك في التطوير العقاري",

  // Auth and OTP
  "resend": "أعد ارسال الرمز",
  "checkCode": "التحقق من الرمز",
  "newAccount": "تسجيل حساب جديد",
  "otpCode": "رمز التحقق",
  "check": "التحقق",
  "haveAccount": "هل لديك حساب؟ تسجيل الدخول",
  "term": "الشروط والأحكام",
  "ok": "موافق",
  "nafaz": "يرجى ادخال الرقم الظاهر في تطبيق نفاذ",
  "next": "التالي",

  // Registration Steps
  "addInfo": "أضف بياناتك الشخصية",
  "nationalNumber": "رقم الهوية",
  "birthday": "تاريخ الميلاد",
  "phoneNumber": "رقم الجوال",
  "national": "الجنسية",
  "soadi": "سعودي",
  "egyption": "مصري",
  "investorType": "نوع المستثمر",

  "nafazCheck": "التحقق عبر نفاذ",

  // Work Info
  "work": "معلومات جهة العمل",
  "workStatus": "الحالة الوظيفية",
  "fillInfo": "املأ البيانات المطلوبة",
  "companyName": "اسم الشركة",
  "companyRecord": "رقم السجل التجاري",
  "uniNumber": "الرقم الموحد",
  "activityType": "نوع النشاط",
  "building": "عقاري",

  // Agreement
  "aggrement": "اتفاقية الاشتراك بالتوقيع الرقمي",
  "confirmAggrement": "أوافق على الاشتراك بالتوقيع الرقمي",
  "save": "حفظ",
  "job": "هل تشغل أي من الوظائف أو المهن التالية؟",

  // Register Success
  "registerComplete": "تم إنشاء حسابك بنجاح",
  "otrpRegister":
      "أضف رمز التحقق لجوالك المسجل في أبشر والمرسل من قبل MOI.GOV.SA",

  // Finance Info
  "income": "مصدر الدخل",
  "yearlyIncome": "الدخل السنوي",
  "investingMoney": "المبلغ المتوقع استثماره",

  // Wallet
  "wallet_title": "المحفظة",
  "wallet_upgrade": "تمت الترقية الي مستثمر موؤهل",
  "wallet_balance": "رصيد المحفظة",
  "available_cash": "النقد المتاح",
  "reserved_cash": "النقد المحجوز",
  "deposit": "إيداع",
  "withdraw": "سحب",

  // Documents & Transactions
  "documents": "مستندات",
  "previous_transactions": "العمليات السابقة",
  "show_all": "إظهار الكل",
  "transactions": "العمليات",
  "deposit_log": "سجل عمليات الإيداع",
  "withdraw_log": "سجل عمليات السحب",
  "bank_log": "سجل الحسابات البنكية",
  "all_transactions_note":
      "جميع العمليات على اختلاف حالتها مقبولة، مرفوضة ... إلخ",
  "verified": "موثق",
  "under_review": "تحت المراجعة",
  "add_bank_account": "إضافة حساب بنكي",
  "account_name": "اسم الحساب",
  "account_name_hint": "حسابي في البنك العربي",
  "iban": "الآيبان",
  "iban_hint": "........",
  "account_number": "رقم الحساب",
  "account_number_hint": "000000000000",
  "bank": "البنك",
  "iban_certificate": "شهادة الآيبان",
  "payment_address": "عنوان الدفع",
  "choose_deposit_method": "اختر طريقة الإيداع",
  "investment_note": "مبلغ الاستثمار يبدأ من 1000 ريال سعودي",
  "bank_transfer": "تحويل بنكي",
  "apple_pay": "Apple Pay",
  "anb_bank_name": "البنك العربي الوطني",
  "fast_bank": "البنك السريع",

  // Example Values
  "name": "الاسم",
  "ibrahim_name": "إبراهيم عبدالله إبراهيم",
  "iban_value": "1000 9987 0098 08937 23",
  "account_number_value": "9987 0098 08937 23",

  // Input
  "enter_deposit_amount": "ادخل مبلغ الإيداع",
  "min_limit_error": "الحد الأدنى هو 1000",
  "min_investment_note": "* الحد الأدنى للاستثمار 1000",
  "pay_with_apple": "ادفع باستخدام Pay",

  // Verification and Filters
  "resend_code": "أعد ارسال الرمز",
  "resend_code_in": "أعد ارسال الرمز في {{seconds}} ثانية",
  "resend_code_In": "أعد ارسال الرمز في",
  "verify_code": "التحقق من الرمز",
  "filter_results_by": "تصفية النتائج حسب",
  "withdraw_amount": "قيمة السحب",
  "withdraw_amount_hint": "#123456",
  "select_account": "اختر الحساب",
  "apply_filters": "تصفية النتائج",
  "verification": "التحقق",
  "otp_sent_to_email": "تم إرسال رمز التحقق إلى البريد الإلكتروني {{email}}",
  "otp_sent_to_Email": "تم إرسال رمز التحقق إلى ",
  "seconds": "ثانية",
  "waiting_for_approval": "بإنتظار الموافقة",
  "confirm_cancel_withdrawal": "تأكيد إلغاء الطلب",
  "are_you_sure_you_want_to_cancel_this_withdrawal":
      "هل أنت متأكد أنك تريد إلغاء طلب السحب هذا؟",
  "cancel": "رجوع",
  "No_data": "لا يوجد بيانات بعد",

  // Address
  "city": "المدينة",
  "district": "الحي",
  "street": "الشارع",
  "building_number": "رقم المبنى",
  "primary_address": "العنوان الرئيسي",

  // Date and Status
  "start_date": "تاريخ البدء",
  "end_date": "تاريخ الانتهاء",
  "request_status": "حالة الطلب",
  "money_transfer_status": "حالة تحويل الأموال",
  "select": "اختر",

  // Bank Operations
  "deposit_operations": "عمليات الإيداع",
  "withdraw_operations": "عمليات السحب",
  "bank_accounts": "الحسابات البنكية",
  "not_verified": "غير موثق",
  "canceled": "إلغاء",
  "approved": "تمت الموافقة",
  "rejected": "مرفوض",
  "view all": "عرض الكل",
  "all opportunity": "كل الفرص",
  "Notifications": "الإشعارات",
  "Cancel": "إلغاء",
  "gregorian_calendar": "التقويم الميلادي",
  "hijri_calendar": "التقويم الهجري",
  "login_first": "الرجاء تسجيل الدخول أولاً للمتابعة",
  "error_required": "هذا الحقل يجب ألا يكون فارغًا",
  "error_short_input": "الإدخال قصير جدًا",
  "error_enter_email": "يرجى إدخال البريد الإلكتروني",
  "error_invalid_email": "يرجى إدخال بريد إلكتروني صالح",
  "error_enter_password": "يرجى إدخال كلمة المرور",
  "error_password_min_length":
      "يجب أن تكون كلمة المرور مكونة من 6 أحرف على الأقل",
  "error_password_format":
      "يجب أن تحتوي كلمة المرور على حرف كبير واحد على الأقل، وحرف صغير واحد على الأقل، ورقم واحد على الأقل",
  "error_reenter_password": "يرجى إعادة إدخال كلمة المرور",
  "error_password_mismatch": "كلمة المرور غير متطابقة",
  "error_number_max": "القيمة يجب أن تكون رقماً وأقل من أو تساوي 100",
  "error_required_iban": "الآيبان مطلوب",
  "error_invalid_iban":
      "يرجى إدخال رقم آيبان  صالح مكون من 24 رقمًا ويبدأ بـ SA",
  "error_required_crn": "يرجى إدخال رقم السجل التجاري",
  "error_invalid_crn":
      "رقم السجل التجاري يجب أن يتكون من 10 أرقام صحيحة ويبدأ برقم غير صفري",
  "error_enter_id": "يرجى إدخال القيمة",
  "error_id_numbers_only": "يجب أن تحتوي القيمة على أرقام فقط",
  "error_id_max_length": "يجب ألا تزيد القيمة عن 10 أرقام",
  "error_required_account_number": "رقم الحساب مطلوب",
  "error_not_zero": "القيمة يجب أن تكون أكبر من 0",
  "view_agreement": "للإطلاع على اتفاقية التوقيع الرقمي ",
  "click_here": "اضغط هنا",
  "confirmCreditAccess":
      "أوافق على الاطلاع على معلوماتي الائتمانية لدى سمة وبيان وتبادل المعلومات الائتمانية",
  "enter_nafaz_code": "يرجى ادخال الرقم الظاهر في تطبيق نفاذ",
  "invalid_birth_date":
      "تاريخ الميلاد ليس صحيحا.. يرجي الرجوع وتعديل تاريخ الميلاد",
  "missing_individual_address": "يرجي تسجيل العنوان الخاص بك وإعادة المحاولة",
  "missing_company_address": "يرجي تسجيل العنوان الخاص بالشركة وإعادة المحاولة",
  "nafaz_failed_title": "فشل التحقق",
  "nafaz_failed_desc": "هل ترغب في إعادة إرسال الرمز؟",
  "yes": "نعم",
  "signature_title": "التوقيع",
  "investment_agreement_title": "اتفاقية الاستثمار",
  "investment_agreement_note":
      "برجاء تحميل الإتفاقية و الإطلاع على كامل بنودها, ثم قم بالضغط على توقيع لتوقيع الإتفاقية و تفعيل حسابك الاستثماري.",
  "view_file": "عرض الملف",
  "sign_agreement": "توقيع الاتفاقية",
  "error_timeout": "انتهت مهلة الطلب. يرجى المحاولة مرة أخرى.",
  "error_no_connection": "لا يوجد اتصال بالإنترنت. يرجى التحقق من الاتصال.",
  "error_http_failure": "فشل في الطلب. يرجى المحاولة مرة أخرى.",
  "error_invalid_format": "تنسيق الاستجابة غير صالح. يرجى المحاولة مرة أخرى.",
  "error_authentication_required":
      "يتطلب تسجيل الدخول. يرجى تسجيل الدخول أولاً.",
  "error_unexpected": "حدث خطأ غير متوقع. يرجى المحاولة مرة أخرى.",
  "investment_portfolio": "المحفظة الاستثمارية",
  "wallet_value": "قيمة المحفظة",
  "revenue": "العائد",
  "revenue_rate": "معدل العائد",
  "view_more": "عرض المزيد",
  "partner_in_real_estate": "شريكك في التطوير العقاري",
  "start_investment_journey": "ابدأ رحلتك الاستثمارية معنا",
  "investment_opportunities": "الفرص الاستثمارية",
  "total_investments": "إجمالي الاستثمارات",
  "bank_account_required": "يجب إنشاء حساب بنكي حتى نتمكن من بدء الاستثمار",
  "create_bank_account": "إنشاء حساب بنكي",
  "welcome_back": "أهلاً بك",
  "press_back": "اضغط رجوع",
  "more_times_to_close": "مرة أخرى للخروج من التطبيق",
  "visitor": "زائر",
  "invalid_index": "فهرس غير صالح",
  "guest_user_message":
      "عذرًا، لا يمكنك المتابعة. يُرجى التسجيل أولاً لإكمال العملية.",
  "financing_amount": "مبلغ التمويل",
  "financing_duration": "مدة التمويل",
  "months": "أشهر",
  "risk_rating": "تصنيف المخاطر",
  "opportunity_return": "العائد على الفرصة",
  "annual_profit_rate": "معدل الربح السنوي",
  "monthly_profit_rate": "معدل الربح الشهري",
  "company_participation": "نسبة مشاركة الشركة في التمويل",

  "no_title": "بدون عنوان",
  "enter_investment_amount": "ادخل مبلغ الاستثمار هنا",
  "invest": "استثمر",
  "risk_disclaimer": "بيان المخاطر",
  "risk_disclaimer_description":
      "أقر بالاطلاع على الشروط والأحكام الخاصة بالوكالة بالاستثمار عبر منصة ذرى للتمويل الجماعي بالدين، وأُقِر بأنني على دراية بالمخاطر المحتملة، على سبيل المثال لا الحصر مخاطر الخسارة ومخاطر توقف المنصة ومخاطر عدم توزيع محفظة الاستثمار وجميع المخاطر المرتبطة بأنشطة الاستثمار. أفهم أن الاستثمار عبر المنصة يحمل درجة عالية من المخاطرة ولا يضمن تحقيق عوائد، وأن منصة ذرى لا تضمن حماية رأس المال أو تتحمل مسؤولية الخسائر، كما أن الاستثمار لا يُعد وديعة مصرفية أو منتجاً مضموناً. اطلعت على تفاصيل الفرصة الاستثمارية قبل اتخاذ القرار، وأدرك أن العوائد ستوزع حسب الجدول الزمني المحدد، بعد خصم رسوم الوكالة بالاستثمار المنصوص عليها في تفاصيل الفرصة.",
  "cancel_investment_title": "إلغاء الإستثمار",
  "cancel_investment_description":
      "هل أنت متأكد من رغبتك في إلغاء الاستثمار؟ لا يمكن التراجع عن هذه العملية.",
  "confirm_cancel_investment": "تأكيد الإلغاء",
  "no_conflict_of_interest": "لا يوجد تعارض مصالح",
  "payment_month": "وقت السداد (بالشهر)",
  "principal_amount": "المبلغ الأساسي",
  "profit": "الأرباح",
  "platform_fee": "رسوم الوكالة",
  "net_profit": "الربح الصافي",
  "total": "المجموع",
  "covered": "تم تغطية",
  "remaining_days": "متبقي",
  "days": "يوم",
  "minimum_investment": "الحد الأدنى للاستثمار هو",
  "currency_sar": "ريال",
  "owner_cannot_invest": "لا يمكنك الاستثمار لأنك مالك الفرصة",
  "already_subscribed": "لقد تم الإستثمار بالفعل",
  "cancel_investment": "إلغاء الإستثمار",
  "investment_hint": "ادخل مبلغ الاستثمار هنا",
  "opportunity_details": "تفاصيل الفرصة",
  "about_opportunity": "عن الفرصة",
  "payment_schedule": "جدول السداد",
  "attachments": "المرفقات",
  "conflict_of_interest": "تعارض المصالح",
  "other_opportunities": "فرص أخرى",
  "choose_date": "اختر التاريخ",
  "pending_approval": "بانتظار الموافقة",
  "cancelled": "إلغاء",
  "pending": "قيد الانتظار",
  "paid": "مدفوع",
  "returned": "مرتجع",
  "view_all": "عرض الكل",
  // About Us
  "about_us":
      "شركة تقنية مالية متخصصة في تمويل مشاريع التطوير العقاري، وتربط المستثمرين الأفراد والمؤسسات بفرص استثمارية في قطاع التطوير العقاري بصيغة المرابحة، وتهدف العملية إلى توفير السيولة لمشاريع التطوير العقاري والفواتير وعائد استثماري للممولين.",
  "your_investment_summary": "ملخص استثماراتك",
  "no_data": "لا توجد بيانات",
  "no_name": "بدون اسم",
  "investment_status_pending": "بانتظار الموافقة",
  "investment_status_approved": "تمت الموافقة",
  "investment_status_rejected": "مرفوض",
  "investment_status_cancelled": "إلغاء",
  "collected_profits": "إجمالي الأرباح المحصلة",
  "active_investments": "إجمالي الاستثمارات القائمة",
  "expected_total_profit": "إجمالي العائد المتوقع",
  "investment_summary": "ملخص استثماراتك",

  "status_active": "نشط",
  "status_closed": "مغلقه",
  "status_on_hold": "معلقة",
  "status_paid": "تم السداد",
  "status_canceled": "إلغاء",
  "status_overdue": "متعثر",
  "status_unknown": "غير معروف",
  "your_info": "معلوماتك",
  "settings": "الإعدادات",
  "contact_us": "تواصل معنا",
  "others": "أخرى",
  "personal_info": "المعلومات الشخصية",
  "kyc_form": "نموذج معرفة العميل",
  "bank_info": "المعلومات البنكية",
  "manage_notifications": "إدارة الإشعارات",
  "language": "اللغة",
  "change_password_pin": "كلمة السر ورمز الدخول",
  "choose_language": "اختر اللغة",
  "arabic": "Arabic - العربية",
  "english": "English - الإنجليزية",
  "support_tickets": "تذاكر الدعم",
  "sharia_committee": "اللجنة الشرعية",
  "about us": "عن ذرى",
  "financial_reports": "القوائم المالية",
  "faq": "الأسئلة الشائعة",
  "articles": "المقالات",
  "terms_conditions": "الشروط والأحكام",
  "logout": "تسجيل الخروج",
  "beneficiary_name": "اسم المستفيد",
  "iban_number": "رقم الآيبان",
  "save_changes": "حفظ التغييرات",
  "id_number": "رقم الهوية",
  "phone_number": "رقم الجوال",
  "delete_my_account": "حذف حسابي",
  "you_can_reach_us_through": "يمكنك التواصل مع ذرى عن طريق:",
  "email_us": "راسلنا عبر البريد الإلكتروني",
  "call_us": "اتصل بنا",
  "working_hours": "ساعات العمل الرسمية",
  "working_hours_text":
      "من الأحد إلى الخميس من الساعة 9 صباحًا إلى الساعة 5 مساءًا",
  "select_inquiry_type": "اختر نوع الاستفسار",
  "write_message_here": "اكتب رسالتك هنا",
  "message_required": "يجب إدخال رسالة",
  "message_max_length": "يجب ألا تزيد الرسالة عن 250 حرفًا",
  "send": "إرسال",
  "year": "السنة",
  "quarter": "الربع",
  "view_report": "تحميل التقرير",
  "notifications": "الإشعارات",
  "notification_title": "إشعار مهم",
  "notification_description":
      "تمت الموافقة على استثمارك الجديد. يمكنك الآن متابعة الأرباح من لوحة التحكم.",
  "notification_time_ago": "قبل ساعتين",
  "job_status": "الحالة الوظيفية",
  "government_sector": "قطاع حكومي",
  "private_sector": "قطاع خاص",
  "businessman": "رجل أعمال",
  "retired": "متقاعد",
  "unemployed": "غير موظف",
  "student": "طالب",
  "terms_conditions_title": "الشروط والأحكام",

  "terms_intro": "المقدمة",
  "terms_intro_list1":
      "تخولك منصة ذرَى للتمويل الجماعي بالبدء في استخدام الموقع...",
  "terms_intro_list2": "يجب عليك قراءة الشروط والأحكام بعناية...",

  "terms_eligibility": "معايير الأهلية للتسجيل:",
  "terms_eligibility_list1": "للدخول إلى الموقع، يجب أن يكون عمرك 18 سنة...",
  "terms_eligibility_list2": "عند التسجيل كمستثمر أو ممول، قد يُطلب منك...",

  "terms_illegal": "ما لا يجوز للمستخدمين القيام به:",
  "terms_illegal_list1": "نشر أي مواد من الموقع...",
  "terms_illegal_list2": "البيع أو التأجير...",
  "terms_illegal_list3": "عرض أي مواد...",
  "terms_illegal_list4": "إعادة إنتاج أو نسخ...",

  "terms_prohibited": "الاستخدام غير المسموح به:",
  "terms_prohibited_list1": "لا يجوز استخدام الموقع لأي سبب غير مشروع...",
  "terms_prohibited_list2": "يحظر توزيع أي فيروسات...",

  "terms_fees": "تفاصيل الرسوم مقابل الخدمة المقدمة:",
  "terms_fees_list1": "يلتزم مقدم الطلب بدفع رسوم إدارية...",

  "terms_warranty": "الضمانات:",
  "terms_warranty_list1": "لا تقدم منصة ذرَى أي ضمانات صريحة...",

  "terms_liability": "حدود المسؤولية:",
  "terms_liability_list1": "ذرَى غير مسؤولة عن أي خسائر مباشرة...",
  "terms_liability_list2": "لا تلتزم ذرَى بأي تعويض مالي...",

  "terms_conflict_policy": "سياسة تضارب المصالح:",
  "terms_conflict_policy_list1": "تحرص ذرَى على التعامل بنزاهة...",

  "terms_dispute": "القانون وتسوية النزاعات:",
  "terms_dispute_list1":
      "تخضع هذه الشروط والأحكام لقوانين المملكة العربية السعودية...",

  "terms_general": "أحكام عامة:",
  "terms_general_list1": "يجوز لمنصة ذرَى تعديل هذه الشروط...",
  "terms_general_list2": "لا يعتبر أي تأخير...",

  "terms_obligations": "من الواجب عليك أن لا:",
  "terms_obligations_list1": "عدم إعادة إنتاج أو مشاركة...",
  "terms_obligations_list2": "عدم تقديم معلومات مزيفة...",
  "about_us_title": "عن ذرَى",
  "about_us_slogan": "شريكك في التطوير العقاري",
  "about_us_subtitle": "عن ذرى للتمويل الجماعي بالدين",
  "about_us_description":
      "ذرى هي منصة تمويل جماعي مرخصة تقدم فرص استثمارية في القطاع العقاري من خلال التمويل بالدين، وتوفر حلولاً مبتكرة للمستثمرين والمطورين.",
  "delete_account_title": "حذف الحساب",
  "delete_account_message":
      "هل أنت متأكد أنك تريد حذف حسابك بشكل نهائي؟ لا يمكن التراجع عن هذا الإجراء.",
  "delete_account_button": "حذف الحساب",
  "delete_account_success": "تم حذف الحساب بنجاح",
  "logout_title": "نراك قريبًا",
  "logout_message": "هل أنت متأكد أنك تريد تسجيل الخروج؟",
  "logout_button": "تسجيل الخروج",
  "change_password": "تغير كلمة السر",
  "old_password": "كلمة المرور القديمة",
  "new_password": "كلمة المرور الجديدة",
  "confirm_password": "التحقق من كلمة السر",
  "notification_settings": "إعدادات الإشعارات",
  "email_notifications": "إشعارات البريد الالكتروني",
  "general_notifications": "الإشعارات العامة",
  "new_opportunities": "فرص جديدة",
  "full_name": "الاسم",
  "ticket_type": "نوع التذكرة",
  "description": "الوصف",
  "send_ticket": "إرسال تذكرة",
  "sharia_title": "الشريعة الإسلامية",
  "sharia_intro":
      "نحرص في شركة ذرى للتمويل الجماعي بالدين على الامتثال لأحكام الشريعة الإسلامية في كافة تعاملاتنا، ويتم ذلك من خلال تعيين وإشراف دار المراجعة الشرعية كمستشار شرعي للإشراف وتقديم المشورة بشأن توافق أعمال الشركة مع الضوابط والمعايير الشرعية.",
  "sharia_bullet_1":
      "إعداد المعايير الشرعية التي تنقيد بها إدارة الشركة عند الاستثمار.",
  "sharia_bullet_2":
      "مراجعة واعتماد المستندات الخاصة بالشركة بما في ذلك الشروط والأحكام، اتفاقية الاشتراك، السياسات والإجراءات، وغيرها من المستندات اللازمة لعملية الاعتماد.",
  "sharia_bullet_3":
      "التحقق من التزام المنصة بقرارات اللجنة في منتجاتها وعقودها.",
  "sharia_bullet_4":
      "الرد على الاستفسارات الموجهة من إدارة الشركة والمتعلقة باستثماراتها أو أنشطتها.",
  "sharia_bullet_5":
      "الإشراف والمراقبة على أنشطة الشركة لضمان توافقها مع الضوابط والمعايير الشرعية.",
  "sharia_download_label": "للإطلاع والتحميل",
  "Available": "الفرص المتاحة",
  "Completed": "الفرص المكتملة",
  "All": "جميع الفرص",

  // new ui
  "login_welcome_title": "أهلاً وسهلاً!",
  "login_welcome_subtitle": "ادخل معلومات الحساب للإستكمال",
  "login_email_label": "البريد الإلكتروني",
  "login_email_hint": "أدخل عنوان بريدك الإلكتروني",
  "login_password_label": "كلمة المرور",
  "login_password_hint": "أدخل كلمة المرور",
  "login_forgot_password": "نسيت كلمة المرور",
  "login_button": "تسجيل الدخول",
  "login_create_account": "إنشاء حساب",

  // Register Screen
  "register_title": "إنشاء حساب جديد",
  "register_type": "نوع المسجل",
  "register_email": "البريد الإلكتروني",
  "register_email_hint": "أدخل عنوان بريدك الإلكتروني",
  "register_password": "كلمة المرور",
  "register_password_hint": "************",
  "register_confirm_password": "تأكيد كلمة المرور",
  "register_confirm_password_hint": "أدخل تأكيد كلمة المرور",
  "register_terms": "أوافق على سياسات الخصوصية والشروط والأحكام",
  "register_submit": "إرسال رمز التحقق",

  // Password rules
  "password_rule_uppercase": "تحتوي على حرف كبير واحد على الأقل (A-Z)",
  "password_rule_lowercase": "تحتوي على حرف صغير واحد على الأقل (a-z)",
  "password_rule_number": "تحتوي على رقم واحد على الأقل (0-9)",
  "password_rule_length": "الطول لا يقل عن 8 أحرف",
  "password_rule_no_spaces": "لا تحتوي على مسافات",
  "individual": "فرد",
  "company": "شركة",

  "register_info_title": "المعلومات الأساسية",
  "register_nationality": "الجنسية",
  "register_select_nationality": "اختر الجنسية",
  "register_id": "الهوية الوطنية/الإقامة",
  "register_id_hint": "ادخل رقم الهوية الوطنية أو الإقامة",
  "register_phone": "رقم الجوال",
  "register_phone_hint": "5xxxxxxxx",
  "register_phone_rule": "ابدأ رقم الجوال بـ 5",
  "register_birthdate": "تاريخ الميلاد",
  "register_birthdate_hint": "اختر تاريخ الميلاد",
  "register_hijri_date": "التاريخ الهجري المكافئ",
  "register_hijri_hint": "yyyy-mm-dd",
  "register_signature_title": "التوقيع الرقمي لإتفاقية الإشتراك",
  "register_signature_terms": "أوافق على الإشتراك بإستخدام التوقيع الرقمي",
  "done": "تم",
  "gregorian": "الميلادي",
  "hijri": "الهجري",
  "onboard_title_1": "نمو طموح ومستمر",
  "onboard_desc_1":
      "قدمت منصة ذرى متوسط عوائد سنوية بلغت %14.44 على الاستثمارات المنفذة، ما يجعلها خيارًا جذابًا لتنمية رأس المال.",

  "onboard_title_2": "أمان واستثمار موثوق",
  "onboard_desc_2":
      "منصتنا مرخصة من البنك المركزي السعودي وتعمل تحت إشرافه المباشر لضمان أعلى درجات الأمان والشفافية في كل عملية تمويل واستثمار.",

  "onboard_title_3": "التزام كامل في التحصيل",
  "onboard_desc_3":
      "نجحت منصة ذرى في تحقيق نسبة تحصيل كاملة 100% من المبالغ المستحقة، مما يعكس فعالية الإدارة المالية وكفاءة آليات التحصيل.",

  "forget_password_title": "إستعادة كلمة المرور",
  "forget_password_section_title": "المعلومات الأساسية",
  "email_hint": "أدخل عنوان بريدك الإلكتروني",
  "national_id": "الهوية/الوطنية الإقامة",
  "national_id_hint": "ادخل رقم الهوية الوطنية أو الإقامة",
  "reset_password_title": "إستعادة كلمة المرور",
  "password_hint": "************",
  "password_rule_upper": "تحتوي على حرف كبير (A-Z)",
  "password_rule_lower": "تحتوي على حرف صغير (a-z)",
  "password_rule_spaces": "لا تحتوي على مسافات",
  "confirm_password_hint": "أدخل تأكيد كلمة المرور",
  "confirm_password_required": "الرجاء تأكيد كلمة المرور",
  "passwords_not_match": "كلمة المرور غير متطابقة",
  "otp_enter_code": "ادخل رمز التحقق",
  "otp_sent_email": "أرسلنا رمز لبريدك الإلكتروني بالأسفل للتحقق من الهوية",
  "otp_sent_phone": "أرسلنا رمز لرقم الجوال بالأسفل للتحقق من الهوية",
  "otp_not_received": "لم تحصل على الرمز؟ ",
  "otp_resend_request": "طلب إعادة إرسال الرمز",
  "otp_resend_in": "أعد ارسال الرمز في @seconds ثواني",
  "register_info_basic": "المعلومات الأساسية",
  "register_info_nationality": "الجنسية",
  "register_info_nationality_hint": "اختر الجنسية",
  "register_info_id_label": "الهوية الوطنية/الإقامة",
  "register_info_id_hint": "ادخل رقم الهوية الوطنية أو الإقامة",
  "register_info_phone_label": "رقم الجوال",
  "register_info_phone_hint": "5xxxxxxxx",
  "register_info_phone_hint_text": "ابدأ رقم الجوال بـ 5",
  "register_info_birthdate_label": "تاريخ الميلاد",
  "register_info_birthdate_hint": "تاريخ الميلاد",
  "register_info_hijri_label": "التاريخ الهجري المكافئ",
  "register_info_hijri_hint": "yyyy-mm-dd",
  "register_info_signature_title": "التوقيع الرقمي لإتفاقية الإشتراك",
  "register_info_terms": "أوافق على الإشتراك بإستخدام التوقيع الرقمي",
  "register_credit_terms":
      "أوافق على الإطلاع علي معلوماتي الائتمانية لدي سمة وبيان وتبادل المعلومات الإئتمانية",
  "view": "إستعراض",
  "month_january": "يناير",
  "month_february": "فبراير",
  "month_march": "مارس",
  "month_april": "أبريل",
  "month_may": "مايو",
  "month_june": "يونيو",
  "month_july": "يوليو",
  "month_august": "أغسطس",
  "month_september": "سبتمبر",
  "month_october": "أكتوبر",
  "month_november": "نوفمبر",
  "month_december": "ديسمبر",
  "hijri_muharram": "محرم",
  "hijri_safar": "صفر",
  "hijri_rabi_al_awwal": "ربيع الأول",
  "hijri_rabi_al_thani": "ربيع الآخر",
  "hijri_jumada_al_ula": "جمادى الأولى",
  "hijri_jumada_al_thania": "جمادى الآخرة",
  "hijri_rajab": "رجب",
  "hijri_shaban": "شعبان",
  "hijri_ramadan": "رمضان",
  "hijri_shawwal": "شوال",
  "hijri_dhul_qidah": "ذو القعدة",
  "hijri_dhul_hijjah": "ذو الحجة",
  "back": "السابق",

  "fund_size": "حجم التمويل",
  "annual_return": "عائد الاستثمار السنوي",
  "coverage": "التغطية",
  "days_left": "الأيام المتبقية",
  "day": "يوم",
  "view_opportunity": "استعراض الفرصة",
  "investment_project": "مشروع استثماري",
  "by_undefined_company": "بواسطة شركة غير محددة",
  "one_step_away_from_investment": "أنت على بُعد خطوة من بدء استثمارك!",
  "please_add_balance_to_start_investment":
      "يُرجى إضافة رصيد إلى المحفظة لبدء الاستثمار",
  "add_balance": "إضافة رصيد",
  "view_all_opportunities": "عرض كل الفرص",
  "your_investment_wallet_balance": "رصيد محفظتك الاستثمارية",
  "investment_transactions": "عمليات الاستثمار",
  "filter": "تصفية",
  "no_investments_now": "لا توجد استثمارات حالياً",
  "opportunity_name": "اسم الفرصة",
  "investment_amount": "مبلغ الاستثمار",
  "investment_duration": "مدة الاستثمار",
  "investment_date": "تاريخ الاستثمار",
  "expected_profit": "العوائد المتوقعة",
  "realized_profit_in_wallet": "العوائد المحققة بالمحفظة",
  "status": "الحالة",
  "filter_investment_transactions": "تصفية عمليات الاستثمار",
  "search_in_all_results": "بحث نصي في كافة النتائج",
  "investment_status": "حالة الاستثمار",
  "please_select": "يرجى التحديد",
  "start_date_range": "بداية النطاق الزمني",
  "end_date_range": "نهاية النطاق الزمني",
  "cancel_all_filters": "إلغاء جميع التصفية",
  "investment_word": "إستثمار",
  "active_investment_amount_count": "عدد المبالغ الاستثمارات القائمة",
  "active_investment_amounts": "مبالغ الإستثمارات القائمة",
  "total_investment_count": "إجمالي عدد الإستثمارات",
  "total_expected_profit": "إجمالي العائد المتوقع",
  "total_invested_amount": "إجمالي المبالغ المستثمرة",
  "total_realized_profit": "إجمالي الأرباح المحصلة",
  "monthly_profits": "الأرباح الشهرية",
  "expected_profits": "الأرباح المتوقعة",
  "realized_profits": "الأرباح المحصلة",
  "delayed_profits": "الأرباح المتعثرة",
  "no_years_available": "لا توجد سنوات متاحة حالياً",
  "no_valid_investment_dates":
      "لم يتم العثور على أي استثمارات تحتوي على تواريخ صالحة.",
  "close": "إغلاق",
  "january": "يناير",
  "february": "فبراير",
  "march": "مارس",
  "april": "أبريل",
  "may": "مايو",
  "june": "يونيو",
  "july": "يوليو",
  "august": "أغسطس",
  "september": "سبتمبر",
  "october": "أكتوبر",
  "november": "نوفمبر",
  "december": "ديسمبر",
  "by": "بواسطة",
  "fund_goal": "هدف الصندوق",
  "return_on_investment": "العائد على الاستثمار",
  "risk_low": "منخفض",
  "risk_medium": "متوسط",
  "risk_high": "مرتفع",
  "start_first_investment": "ابدأ أول استثماراتك",
  "upgrade_to_qualified_investor": "الترقية إلى مستثمر مؤهل",
  "qualified_investor_description":
      "تمتع بمزايا إضافية وفرص حصرية مع الترقية لمستثمر مؤهل – لأصحاب الخبرة والملاءة المالية فقط.",
  "activate_qualified_investor_benefits": "فعّل مزاياك كمستثمر مؤهل اليوم",
  "upgrade_request_under_review": "طلب الترقية قيد المراجعة",
  "upgrade_request_review_description":
      "تم استلام طلبك للترقية إلى مستثمر مؤهل، وهو حالياً قيد المراجعة من قبل فريقنا. سيتم إشعارك فور الموافقة أو في حال الحاجة إلى مستندات إضافية.",
  "qualified_investor": "مستثمر مؤهل",
  "qualified_investor_approved_description":
      "تمت الموافقة على ترقيتك كمستثمر مؤهل! يمكنك الآن الاستفادة من فرص استثمارية حصرية ومزايا إضافية ضمن المنصة.",
  "all_investment_opportunities": "كل الفرص الاستثمارية",
  "home": "الرئيسية",
  "no_opportunities_available": "لا توجد فرص متاحة حالياً",
  "new_opportunities_soon": "سيتم عرض الفرص الجديدة بمجرد توفرها.",
  "opportunities": "الفرص",
  "wallet": "المحفظة",
  "available_opportunities": "الفرص المتاحة",
  "upcoming_opportunities": "الفرص القادمة",
  "completed_opportunities": "الفرص المكتملة",
  "discover_investment_opportunity": "اكتشف هذه الفرصة الاستثمارية المميزة:",
  "project_code": "رمز المشروع:",
  "share_via_tharaa": "شارك عبر تطبيق ذرى!",
  "fund_duration": "مدة التمويل",
  "month": "شهر",
  "distributions": "التوزيعات",
  "quarterly": "ربع سنوي",
  "payment_number": "الدفعة",
  "due_date": "تاريخ الاستحقاق",
  "interest": "الأرباح",
  "taxes_and_fees": "رسوم الوكالة بالاستثمار (شاملة ضريبة القيمة المضافة)",
  "total_payment": "إجمالي الدفع",
  "first": "الأولى",
  "second": "الثانية",
  "third": "الثالثة",
  "fourth": "الرابعة",
  "fifth": "الخامسة",
  "sixth": "السادسة",
  "seventh": "السابعة",
  "eighth": "الثامنة",
  "ninth": "التاسعة",
  "tenth": "العاشرة",
  "investment_agreement": "إتفاقية الإستثمار",
  "investment_agreement_description":
      "يرجى تحميل ملف الاتفاقية ومراجعة جميع بنودها، ثم الضغط على زر “توقيع” لتوقيع الاتفاقية وتفعيل حساب الاستثمار الخاص بك",
  "download": "تحميل",
  "disclosures": "الإفصاحات",
  "withdraw_investment": "سحب الاستثمار",
  "withdraw_investment_confirmation":
      "أنت على وشك سحب الاستثمار. هل أنت متأكد من العملية؟",
  "owner_investment_restriction": "لا يمكن للمالك الاستثمار في فرصة يمتلكها.",
  "already_invested_title": "أنت مستثمر في هذه الفرصة",
  "already_invested_description": "لقد استثمرت بالفعل في هذه الفرصة.",
  "riyal": "ريال",
  "info": "معلومة",
  "success": "تم بنجاح",
  "investment_operations": "عمليات الاستثمار",
  "no_deposit_operations": "لا توجد عمليات إيداع بعد",
  "no_withdraw_operations": "لا توجد عمليات سحب بعد",
  "date_range": "نطاق التاريخ",
  "until": "حتى",
  "search": "بحث",
  "bank_account": "الحساب البنكي",
  "investment_account_prefix": "حساب الاستثمار -",
  "transaction_amount": "مبلغ العملية",
  "transaction_date": "تاريخ العملية",
  "complete_verification": "إستكمال التحقق",
  "cancel_withdrawal_title": "إلغاء عملية السحب",
  "cancel_withdrawal_body": "سيتم إلغاء عملية السحب، هل تود الإستكمال؟",
  "cancel_withdrawal_confirm": "استكمال إلغاء عملية السحب",
  "investment_account": "حساب الإستثمار",
  "unknown_source": "مصدر غير معروف",
  "withdraw_from_balance": "سحب من الرصيد",
  "transfer_amount": "مبلغ التحويل",
  "transfer_to": "التحويل إلى",
  "select_bank_account": "اختر الحساب البنكي",
  "total_transfer_fees": "إجمالي الرسوم على الحوالة",
  "total_deducted_amount": "إجمالي المبلغ المخصوم",
  "upgrade_instructions":
      "لترقية حسابك اختر متطلبًا واحدًا على الأقل مما يلي، مع إرفاق المستندات التي تثبت ذلك",
  "requirement_annual_income":
      "أن لا يقل الدخل السنوي أو الأرباح السنوية عن 600 ألف ريال سعودي في السنتين الأخيرتين",
  "requirement_net_assets":
      "إجمالي الأصول الشخصية لا تقل عن 3 مليون ريال سعودي",
  "requirement_experience":
      "خبرة عمل لا تقل عن 3 سنوات في القطاع المالي أو في وظيفة مهنية تتعلق بالتمويل أو الاستثمار",
  "requirement_certification":
      "شهادة مهنية معترف بها تتعلق بالتمويل والاستثمار",
  "submit": "إرسال",
  "select_at_least_one_requirement":
      "يرجى اختيار متطلب واحد على الأقل ورفع مستنداته",
  "upload_required_documents": "يرجى رفع مستندات للمتطلبات المحددة",
  "filter_deposit_history": "تصفية سجل عمليات الإيداع",
  "filter_withdraw_history": "تصفية سجل عمليات السحب",
  "search_in_results": "بحث نصي في كافة النتائج",
  "select_request_status": "يرجى تحديد حالة الطلب",
  "select_money_transfer_status": "يرجى تحديد حالة تحويل الأموال",
  "available_balance": "المحفظة",
  "trusted_bank_accounts": "الحسابات البنكية الموثوقة",
  "unknown": "غير معروف",
  "arab_bank": "البنك العربي",
  "iban_copied": "تم نسخ رقم الآيبان",
  "account_copied": "تم نسخ رقم الحساب",
  "choose_payment_method": "اختر طريقة إضافة المبلغ",
  "credit_or_debit_card": "بطاقة إئتمانية/بنكية",
  "bank_card": "بطاقة بنكية",
  "deposit_method_selected": "تم اختيار طريقة الإيداع",
  "cardholder_name": "اسم حامل البطاقة",
  "card_number": "رقم البطاقة",
  "expiry_date": "تاريخ إنتهاء السجل التجاري",
  "month_year": "شهر/سنة",
  "cvv_code": "رمز الأمان",
  "save_card_for_future": "أحفظ البطاقة لأي دفوعات مستقبلية",
  "primary_account": "محفظتك الاستثمارية",
  "alternate_account_name": "اسم الحساب البديل",
  "account_owner_name": "اسم صاحب الحساب",
  "transfer_note_title": "تنويه قبل التحويل",
  "transfer_note_description":
      "الرجاء التأكد من أن التحويل يكون عن طريق حساب تمت إضافته مسبقاً في ذرى",
  "total_surplus_balance": "إجمالي الرصيد المتاح",
  "add_balance_button": "إضافة رصيد",
  "withdraw_available_balance": "سحب الرصيد المتاح",
  "attach_account_ownership_proof": "يرجى إرفاق إثبات ملكية الحساب",
  "upload_account_proof_description":
      "يُرجى إرفاق وثيقة تثبت ملكيتك للحساب البنكي بصيغة PDF أو صورة (PNG, JPG) بحجم لا يتجاوز 5 ميجابايت.",
  "continue": "متابعة",
  "select_national_address": "اختر العنوان الوطني المستخدم",
  "address_type": "نوع العنوان",
  "primary": "رئيسي",
  "secondary": "إضافي",
  "add_account": "إضافة الحساب",
  "add_bank_account_info": "إضافة معلومات حساباتك البنكية",
  "add_bank_account_subtitle":
      "يجب إضافة حسابك البنكي قبل تحويل أي رصيد إلى محفظتك. لن يُسحب أي مبالغ من حسابك. يهدف هذا الإجراء إلى حفظ حساباتك البنكية لتحويل الاستثمارات أو الفوائد إليها، ومطابقة الحوالات الواردة.",
  "enter_account_alias_hint": "ادخل اسم بديل للحساب (مثال: حساب الادخار)",
  "select_bank_hint": "يرجى تحديد البنك",
  "bank_account_number": "رقم الحساب البنكي",
  "enter_bank_account_hint": "ادخل رقم الحساب البنكي",
  "enter_iban_hint": "أدخل رقم الآيبان",
  "profile_title": "الملف الشخصي",
  "account_settings": "إعدادات الحساب",
  "language_option": "الإنجليزية English",
  "account_and_settings": "الحساب والإعدادات",
  "face_id_login": "الدخول بواسطة التعرف على الوجه Face ID",
  "help_and_support": "المساعدة والدعم",
  "raise_ticket": "رفع تذكرة",
  "call": "اتصال",
  "message": "مراسلة",
  "call_failed": "تعذر إجراء المكالمة",
  "email_failed": "تعذر فتح تطبيق البريد",
  "about_thara": "عن ذرى",
  "islamic_compliance": "التوافق مع الشريعة الإسلامية",
  "credit_rating": "التصنيف الائتماني",
  "visit_website": "زيارة موقع ذرى",
  "license_note":
      "تُعد \"ذرى للتمويل الجماعي بالدين\" جهة مرخصة وتحت إشراف ورقابة البنك المركزي السعودي، وتحمل الترخيص رقم (84/أ ش/202401). © 2025 جميع الحقوق محفوظة.",
  "about_paragraph":
      "شركة تقنية مالية متخصصة في تمويل مشاريع تطوير العقارات. تقوم \"ذرى\" بربط المستثمرين بالفرص في قطاع العقارات باستخدام عقد المرابحة، مما يوفر السيولة والعوائد.",
  "app_version": "إصدار التطبيق v1.3.09",
  "investment_account_status": "حالة الحساب الإستثماري",
  "account_type": "نوع الحساب",
  "loan_account_status": "حالة حساب الإقراض",
  "upgrade_request_pending": "طلب الترقية قيد المراجعة",
  "already_professional_investor": "أنت بالفعل مستثمر مؤهل",
  "upgrade_to_professional_investor": "الترقية إلى مستثمر مؤهل",
  "disable_account": "إيقاف الحساب",
  "name_in_english": "الاسم بالإنجليزية",
  "account_owner": "مالك الحساب",
  "national_id_or_residence": "الهوية الوطنية / الإقامة",
  "birth_date_gregorian": "تاريخ الميلاد (ميلادي)",
  "mobile_number": "رقم الجوال",
  "email_address": "البريد الإلكتروني",
  "edit": "تعديل",
  "company_name": "اسم الشركة",
  "company_field": "مجال عمل الشركة",
  "commercial_registration": "رقم السجل التجاري",
  "unified_number": "الرقم الموحد",
  "edit_email_title": "تعديل البريد الإلكتروني",
  "new_email_label": "العنوان البريد الإلكتروني الجديد",
  "new_email_hint": "أدخل عنوان بريدك الإلكتروني الجديد",
  "invalid_email_error": "يرجى إدخال بريد إلكتروني صالح",
  "edit_phone_number": "تعديل رقم الجوال",
  "new_phone_number": "رقم الجوال الجديد",
  "enter_new_phone_number": "أدخل رقم الجوال الجديد",
  "enter_valid_phone": "يرجى إدخال رقم جوال صالح",
  "verify_email_title": "ادخل رمز التحقق المرسل عبر البريد الإلكتروني الحالي",
  "verify_email_desc":
      "أرسلنا رمزًا إلى بريدك الإلكتروني الحالي للتحقق من الهوية",
  "verify_email_check_spam": "تأكد من الرسائل غير المرغوب فيها أو ",
  "resend_in": "إعادة الإرسال خلال {{seconds}}",
  "code_resent_success": "تم إرسال الرمز مرة أخرى",
  "enter_otp_for_new_phone": "ادخل رمز التحقق المرسل عبر رقم الجوال الجديد",
  "otp_sent_to_phone": "أرسلنا رمزًا إلى رقمك للتحقق من الهوية",
  "did_not_receive_code": "لم تستلم الرمز؟ ",
  "resend_in_seconds": "إعادة الإرسال خلال {{seconds}} ثانية",
  "notify_new_projects": "تنبيه عند طرح مشاريع استثمارية جديدة على المنصة",
  "notify_financial_operations": "العمليات المالية (إيداع وسحب)",
  "notify_profit_added": "تنبيه عند إضافة الأرباح المستحقة إلى الرصيد",
  "notify_portfolio_performance": "إشعارات تحديثات أداء محفظتك واستثماراتك",
  "notify_articles_materials":
      "إشعار بوصول مقالات أو مواد تثقيفية تدعم قراراتك الاستثمارية",
  "notify_updates_announcements":
      "تنبيه بأحدث التحديثات والإعلانات الصادرة من ذرى",
  "disable_all_notifications": "تعطيل جميع الإشعارات",
  "new_ticket": "تذكرة جديدة",
  "working_hours_notice":
      "عميلنا العزيز\nيرجى ملاحظة أن ساعات العمل تبدأ من الأحد إلى الخميس، من 09:00 صباحًا حتى 05:00 مساءً.",
  "enter_full_name": "أدخل اسمك الكامل",
  "enter_phone_number": "أدخل رقم الجوال",
  "select_ticket_type": "اختر نوع التذكرة",
  "write_message": "اكتب الرسالة",
  "user_name_placeholder": "اسم المستخدم",
  "current_password": "كلمة المرور الحالية",
  "confirm_new_password": "تأكيد كلمة المرور الجديدة",
  "confirm_change_password": "تأكيد تغيير كلمة المرور",
  "rule_uppercase": "تحتوي على حرف كبير واحد على الأقل (A-Z)",
  "rule_lowercase": "تحتوي على حرف صغير واحد على الأقل (a-z)",
  "rule_number": "تحتوي على رقم واحد على الأقل (0-9)",
  "rule_no_spaces": "لا تحتوي على مسافات",
  "rule_min_length": "الطول لا يقل عن 12 حرف",
  "logout_description": "هل أنت متأكد أنك ترغب بتسجيل الخروج من حسابك؟",
  "confirm_logout": "تأكيد الخروج",
  "logout_success": "تم تسجيل الخروج بنجاح",

  "about_thara_title": "عن ذُرى",
  "thara_company_name": "شركة ذُرى للتمويل",
  "thara_vision_summary":
      "رؤيتنا أن نكون الوجهة الأولى للتمويل الاستثماري المبتكر في المملكة.",
  "our_vision": "رؤيتنا",
  "vision_description":
      "أن نكون الشريك المالي الموثوق الذي يقود مستقبل التمويل الاستثماري عبر الابتكار والتقنية والثقة.",
  "our_mission": "رسالتنا",
  "mission_description":
      "تقديم حلول تمويلية واستثمارية آمنة ومتوافقة مع الشريعة الإسلامية، تسهم في دعم المشاريع الناشئة وتطوير الاقتصاد الوطني.",
  "contact_info":
      "البريد الإلكتروني: info@tharaco.sa\nرقم الهاتف: 8001240393\nالموقع الإلكتروني: www.thara.sa",
  "all_rights_reserved": "جميع الحقوق محفوظة.",
  "terms_intro_text":
      "تعرف على الشروط والأحكام الخاصة باستخدام خدمات منصة ذُرى.",
  "terms_footer_text":
      "تؤكد شركة ذُرى للتمويل التزامها الكامل بتطبيق أعلى معايير الشفافية وحماية المستخدمين.",
  "terms_intro_title": "مقدمة",
  "terms_eligibility_title": "أهلية الاستخدام",
  "terms_illegal_title": "الأنشطة غير القانونية",
  "terms_prohibited_title": "الأنشطة المحظورة",
  "terms_fees_title": "الرسوم والتكاليف",
  "terms_warranty_title": "الضمانات",
  "terms_liability_title": "المسؤوليات",
  "terms_conflict_title": "سياسة تضارب المصالح",
  "terms_dispute_title": "حل النزاعات",
  "terms_general_title": "أحكام عامة",
  "terms_obligations_title": "التزامات المستخدم",
  "sharia_compliance_title": "التوافق مع الشريعة الإسلامية",
  "sharia_committee_title": "اللجنة الشرعية",
  "sharia_committee_desc":
      "تعمل اللجنة الشرعية على ضمان توافق جميع معاملات شركة ذُرى مع أحكام الشريعة الإسلامية، وتقوم بمراجعة وتدقيق كافة المنتجات التمويلية والاستثمارية.",
  "sharia_point1": "تشرف اللجنة الشرعية على جميع المنتجات التمويلية.",
  "sharia_point2": "تراجع العقود لضمان توافقها مع أحكام الشريعة.",
  "sharia_point3": "تصدر تقارير سنوية بالمطابقة الشرعية.",
  "sharia_point4": "تتابع تطبيق الفتاوى الشرعية في العمليات.",
  "sharia_point5": "تعتمد العقود والسياسات الخاصة بالمستثمرين.",
  "sharia_certificate_title": "شهادة الإعتماد الشرعي",
  "sharia_certificate_desc":
      "يمكنك تحميل وقراءة شهادة الاعتماد الشرعي الصادرة من اللجنة الشرعية لشركة ذُرى للتمويل.",
  "download_certificate": "تحميل الشهادة",
  "sharia_footer_note":
      "شركة ذُرى للتمويل - جميع المنتجات متوافقة مع الشريعة الإسلامية بإشراف اللجنة الشرعية.",

  "financial_reports_title": "التقارير المالية",
  "no_financial_reports": "لا توجد تقارير مالية حالياً",
  "financial_reports_header":
      "تصفح واطلع على التقارير المالية الربعية والسنوية لشركة ذرى.",
  "financial_year": "السنة المالية ",
  "financial_report_description":
      "يمكنك تحميل التقرير المالي للاطلاع على الأداء المالي للشركة خلال هذه الفترة.",
  "download_report": "تحميل التقرير",
  "no_file_available": "لا يوجد ملف متاح للتنزيل",
  "transfer_source": "مصدر الحوالة",
  "active_status": "فعال",
  "account_deleted_success": "تم حذف الحساب بنجاح",
  "account_type_company": "حساب شركة",
  "account_type_individual": "حساب فردي",
  "account_type_unknown": "غير محدد",
  "status_inactive": "غير نشط",
  "status_not_activated": "لم يتم التفعيل",
  "status_pending": "قيد التقديم",
  "status_not_applied": "لم يتقدم",
  "investor_professional": "مستثمر مؤهل",
  "investor_upgrade_pending": "طلب ترقية قيد المراجعة",
  "investor_upgrade_request": "طلب ترقية المستثمر",
  "investor_unverified": "غير موثق",
  "investor_verified": "مستثمر موثق",
  "indicator": "مؤشر العقار",
  "login_guest": "الدخول كزائر",
  "password_rule_special_char": "تحتوي على رمز خاص واحد على الأقل (!@#\$%^&*)",
  "nafath": "نفاذ",
  "finish": "إبدأ",
  "un_auth": "انتهت الجلسة، برجاء تسجيل الدخول مرة أخرى",
  "notYet": "لم تستحق بعد",
  "investment_limit": "حد الإستثمار",
  "profit_expected": "الأرباح المتوقعة",
  "profit_gained": "الأرباح المحصلة",
  "profit_delayed": "الأرباح المتأخرة",
  "profit_default": "الأرباح المتعثرة",
  "min_required": "يجب إدخال حد أدنى.",
  "value_invalid": "القيمة غير صحيحة.",
  "value_must_be_positive": "يجب أن تكون القيمة أكبر من 0.",
  "min_must_be_1000_or_more": "الحد الأدنى يجب أن يكون 1000 أو أكثر.",
  "max_required": "يجب إدخال حد أعلى.",
  "must_be_multiple_of_1000": "يجب أن يكون مبلغ الاستثمار 1000 أو مضاعفاته.",
  "max_must_be_more_than_min":
      "يجب أن تكون القيمة أكبر من أو تساوي الحد الأدنى (@min).",
  "min_invest_title": "الحد الأدنى للاستثمار في الفرصة",
  "max_invest_title": "الحد الأعلى للاستثمار في الفرصة",
  "auto_invest_created_success": "تم إعداد استثمارك الآلي بنجاح!",
  "auto_invest_updated_success": "تم تحديث استثمارك الآلي بنجاح!",
  "auto_invest_edit_anytime": "يمكنك تعديل تفضيلاتك في أي وقت من لوحة التحكم.",
  "redirecting_now": "سيتم إعادة توجيهك الآن.",
  "auto_invest_title": "الاستثمار الآلي",
  "auto_invest_enabled_now": "الاستثمار الآلي مُفعل حاليًا.",
  "edit_auto_invest_settings": "تعديل الإعدادات",
  "stop_auto_invest": "إيقاف الاستثمار الآلي",
  "auto_invest_title_header": "الاستثمار الآلي من ذرى",
  "auto_invest_subtitle": "استثمر بذكاء، واترك التنفيذ علينا!",

  "auto_invest_feature_simple": "دون تعقيد",
  "auto_invest_feature_simple_desc":
      "كل ما عليك هو تحديد تفضيلاتك، وسيتولى النظام استثمار أموالك تلقائياً في الفرص التي تناسبك.",

  "auto_invest_feature_control": "تحكم كامل",
  "auto_invest_feature_control_desc":
      "اختر المبلغ، مستوى المخاطرة، والمدة المناسبة، وغير ما شئت.",

  "auto_invest_feature_tracking": "متابعة سلسة",
  "auto_invest_feature_tracking_desc":
      "راقب أداء استثماراتك في أي وقت عبر لوحة تحكم موحدة.",

  "auto_invest_feature_flexibility": "مرونة الإيقاف",
  "auto_invest_feature_flexibility_desc":
      "أوقف الاستثمار المخطط له بضغطة زر، في أي لحظة.",

  "auto_invest_feature_free": "بدون رسوم إضافية",
  "auto_invest_feature_free_desc": "خدمة المستشار الآلي متاحة لك مجاناً كلياً.",

  "risk_level": "مستوى المخاطر",
  "risk_level_consent": "بالضغط، فأنت توافق على إفصاح مستوى المخاطر",

  "activate_auto_invest": "تفعيل الاستثمار الآلي",
  "real_estate_title": "تطوير عقاري",
  "invoice_title": "فواتير",

  "package_a_desc": "الباقة المُحتفظة تصل نسبة العوائد إلى %10 - %13 سنوياً",
  "package_b_desc": "الباقة المتوازنة تصل نسبة العوائد إلى %14 - %16 سنوياً",
  "package_c_desc": "باقة نمو تصل نسبة العوائد إلى %16 - %18 سنوياً",

  "duration_6": "حتى 6 أشهر",
  "duration_12": "12 شهراً",
  "duration_18": "أكثر من 12 شهراً",

  "error_select_opportunity": "يجب اختيار نوع واحد على الأقل.",
  "error_min_greater_zero": "الحد الأدنى يجب أن يكون أكبر من 0.",
  "error_max_greater_zero": "الحد الأعلى يجب أن يكون أكبر من 0.",
  "error_max_less_min": "يجب أن يكون الحد الأعلى أكبر أو يساوي الحد الأدنى.",
  "error_amount_must_1000": "يجب أن يكون مبلغ الاستثمار 1000 أو مضاعفاته.",
  "error_select_package": "الرجاء اختيار باقة واحدة على الأقل.",
  "error_select_duration": "الرجاء اختيار مدة الاستثمار.",
  "error_general": "حدث خطأ أثناء حفظ الإعدادات.",

  "success_edit": "تم تحديث استثمارك بنجاح!",
  "success_create": "تم إعداد استثمارك الآلي بنجاح!",
  "edit_auto_invest_preferences": "تعديل تفضيلات الاستثمار الآلي",
  "wizard_title": "الإستثمار الآلي",
  "wizard_step_0": "اختر نوع الفرصة",
  "wizard_step_1": "تخصيص مبلغ الاستثمار",
  "wizard_step_2": "اختيار الباقة",
  "wizard_step_3": "تحديد مدة الاستثمار",

  "wizard_subtitle_multi_select": "يمكنك اختيار أكثر من خيار",
  "biometric_title": "سجل دخول بنظرة!",
  "biometric_subtitle":
      "استخدم الـ Face ID لتسجيل الدخول بدل الرقم السري، أكثر أمانًا وأسهل استخدامًا.",
  "biometric_skip": "ليس الآن",
  "biometric_enable": "فعل التعرف على الوجه Face ID",
  "about": "حول الفرصة",
  "theme": "المظهر",
  "light_mode": "الوضع الفاتح",
  "dark_mode": "الوضع الداكن",
  "browse_faq": "تصفح الأسئلة الأكثر شيوعًا وإجاباتها حول المنصة وخدماتها.",
  "error_required_field": "هذا الحقل مطلوب",
  "error_required_phone": "يرجى إدخال رقم الجوال",
  "error_invalid_saudi_phone": "رقم الجوال يجب أن يبدأ بـ 5 ويتكون من 9 أرقام",
  "enter_amount": "أدخل المبلغ",
  "payment": "الدفع",
  "total_amount": "إجمالي المبلغ",
  "preparing_payment": "جاري تجهيز عملية الدفع...",
  "payment_init_failed": "فشل تهيئة عملية الدفع",
  "success_account":
      "تم إنشاء حسابك بنجاح! يمكنك الآن تسجيل الدخول والاستمتاع بالخدمات.",

  "opportunity_invoice": "فواتير",
  "opportunity_real_state": "تطوير عقاري",

  "duration_6_months": "حتى 6 أشهر",
  "duration_12_months": "12 شهرًا",
  "duration_18_plus_months": "أكثر من 12 شهرًا"
};
