const Map<String, String> en = {
  "Home": "Home",
  "Deals": "Deals",
  "Sales": "Sales",
  "Statistics": "Statistics",
  "Payments": "Payments",
  "Settings": "Settings",
  "Profile": "Profile",
  "Notifications": "Notifications",
  "Help": "Help",
  "Logout": "Logout",
  "Buyer Agreements": "Buyer Agreements",
  "Farmer Agreements": "Farmer Agreements",
  "Supplies": "Supplies",
  "Returns": "Returns",
  "Total Sales Amount": "Total Sales Amount",
  "Total Quantity Sold": "Total Quantity Sold",
  "Number of Buyer Returns": "Number of Buyer Returns",
  "Number of Sales": "Number of Sales",
  "Number of Sales Contracts": "Number of Sales Contracts",
  "Total Returned Quantity": "Total Returned Quantity",
  "SAR": "SAR",
  "Tons": "Tons",
  "Contracts": "Contracts",
  "Buyers": "Buyers",
  "Farmers": "Farmers",
  "Procer": "Procer",
  "Select": "Select",
  "Agreements": "Agreements",
  "Riyadh Dates Market": "Riyadh Dates Market",
  "Al Ahsa Dates Market": "Al Ahsa Dates Market",
  "Rejected": "Rejected",
  "Approved": "Approved",
  "Start Date": "Start Date",
  "End Date": "End Date",
  "Muhammed Elsheikh": "Muhammed Elsheikh",
  "Trades": "Trades",
  "sale_number": "Sale Number",
  "market": "Market",
  "sale_date": "Sale Date",
  "total_quantity": "Total Quantity",
  "product_count": "Product Count",
  "seller": "Seller",
  "delivered": "Delivered",
  "pending": "Pending",
  "Log in to Seasonal Market": "Log in to Seasonal Market",
  "Email": "Email",
  "Enter your email": "Enter your email",
  "Password": "Password",
  "Enter your password": "Enter your password",
  "Login": "Login",
  "Create New Account?": "Create New Account?",
  "Seasonal Market": "Seasonal Market",
  "sign_up": "Sign Up",
  "identity_number": "Identity Number",
  "enter_identity_number": "Enter your Identity Number",
  "phone_number": "Phone Number",
  "date_of_birth": "Date of Birth",
  "email": "Email",
  "enter_email": "Enter your email",
  "gender": "Gender",
  "select": "Select",
  "national_address": "National Address",
  "enter_address": "Enter address",
  "agriculture_number": "Agricultural Number",
  "vat_number": "VAT Number",
  "enter_vat_number": "Enter VAT number",
  "markets": "Markets",
  "password": "Password",
  "enter_password": "Enter your password",
  "confirm_password": "Confirm Password",
  "reenter_password": "Re-enter password",
  "continue": "Continue",
  "Individual": "Individual",
  "Select this option if you are an individual farmer and not an establishment or organization.":
      "Select this option if you are an individual farmer and not an establishment or organization.",
  "Establishments": "Establishments",
  "Select this option if you are a company, organization, or a non-profit entity.":
      "Select this option if you are a company, organization, or a non-profit entity.",
  "Enter agricultural number": "Enter agricultural number",
  "Sign Up": "Sign Up",
  "Please enter your email": "Please enter your email",
  "Please enter a valid email": "Please enter a valid email",
  "Please enter your password": "Please enter your password",
  "Password must be at least 8 characters long, \ninclude an uppercase letter, \nnumber and special character.":
      "Password must be at least 8 characters long, \ninclude an uppercase letter, \nnumber and special character.",
  "Please enter your name": "Please enter your name",
  "Name can only contain letters and spaces":
      "Name can only contain letters and spaces",
  "Name must be at least 2 characters long":
      "Name must be at least 2 characters long",
  "Please enter a number": "Please enter a number",
  "The input must only contain numbers": "The input must only contain numbers",
  "The number must be at least 2 digits long":
      "The number must be at least 2 digits long",
  "Please enter your address": "Please enter your address",
  "Address can only contain letters and spaces":
      "Address can only contain letters and spaces",
  "Address must be at least 2 characters long":
      "Address must be at least 2 characters long",
  "Please enter your phone number": "Please enter your phone number",
  "Please enter a valid phone number": "Please enter a valid phone number",
  "Phone number must be between 8 and 15 digits":
      "Phone number must be between 8 and 15 digits",
  "Please confirm your password": "Please confirm your password",
  "Passwords do not match": "Passwords do not match",
  "Please enter your identity number": "Please enter your identity number",
  "Identity number must contain only numbers":
      "Identity number must contain only numbers",
  "Identity number must not exceed 10 digits":
      "Identity number must not exceed 10 digits",
  "male": "Male",
  "female": "Female",
  "Elryad Market": "Riyadh Market",
  "CEntral Market": "Central Market",

  // Wallet
  "wallet_title": "Wallet",
  "wallet_balance": "Wallet Balance",
  "available_cash": "Available Cash",
  "reserved_cash": "Reserved Cash",
  "deposit": "Deposit",
  "withdraw": "Withdraw",
  "documents": "Documents",
  "previous_transactions": "Previous Transactions",
  "show_all": "Show All",
  "transactions": "Transactions",
  "deposit_log": "Deposit Transactions Log",
  "withdraw_log": "Withdraw Transactions Log",
  "bank_log": "Bank Accounts Log",
  "all_transactions_note": "All transactions regardless of status",
  "verified": "Verified",
  "under_review": "Under Review",
  "add_bank_account": "Add Bank Account",
  "account_name": "Account Name",
  "account_name_hint": "My account at Arab Bank",
  "iban": "IBAN",
  "iban_hint": "........",
  "account_number": "Account Number",
  "account_number_hint": "000000000000",
  "bank": "Bank",
  "iban_certificate": "IBAN Certificate",
  "payment_address": "Payment Address",
  "choose_deposit_method": "Choose Deposit Method",
  "investment_note": "Investment amount starts from 1000 SAR",
  "bank_transfer": "Bank Transfer",
  "apple_pay": "Apple Pay",
  "anb_bank_name": "Arab National Bank",
  "fast_bank": "Fast Bank",
  "name": "Name",
  "ibrahim_name": "Ibrahim Abdullah Ibrahim",
  "iban_value": "1000 9987 0098 08937 23",
  "account_number_value": "9987 0098 08937 23",
  "enter_deposit_amount": "Enter deposit amount",
  "min_limit_error": "Minimum amount is 1000",
  "min_investment_note": "* Minimum investment is 1000",
  "pay_with_apple": "Pay with Pay",

  // OTP & Verification
  "resend_code": "Resend Code",
  "resend_code_In": "Resend code in",
  "verify_code": "Verify Code",
  "otp_sent_to_email": "Verification code has been sent to {{email}}",
  "otp_sent_to_Email": "Verification code has been sent to",
  "seconds": "seconds",
  "waiting_for_approval": "waiting for approval",

  // Filters
  "filter_results_by": "Filter results by",
  "withdraw_amount": "Withdraw Amount",
  "withdraw_amount_hint": "#123456",
  "select_account": "Select Account",
  "apply_filters": "Apply Filters",

  // Others
  "verification": "Verification",
  "city": "City",
  "district": "District",
  "street": "Street",
  "building_number": "Building Number",
  "primary_address": "Primary Address",
  "start_date": "Start Date",
  "end_date": "End Date",
  "request_status": "Request Status",
  "money_transfer_status": "Money Transfer Status",
  "deposit_operations": "Deposit Operations",
  "withdraw_operations": "Withdraw Operations",
  "bank_accounts": "Bank Accounts",
  "not_verified": "Not Verified",
  "canceled": "Canceled",
  "banks": "Banks",
  "view all": "View all",
  "all opportunity": "all opportunity",
  "Cancel": "Cancel",
  "gregorian_calendar": "Gregorian Calendar",
  "hijri_calendar": "Hijri Calendar",
  "login_first": "Please log in first to continue",
  "confirm_cancel_withdrawal": "Confirm Cancellation",
  "are_you_sure_you_want_to_cancel_this_withdrawal":
      "Are you sure you want to cancel this withdrawal request?",
  "confirm": "Confirm",
  "cancel": "Back",
  "back": "Back",
  "No_data": "No Data Founded Yet",
  "login": "Login",
  "forgetPassword": "Forgot Password",
  "forgetPassDesc":
      "Please enter your email so we can send you a verification code.",
  "confirmEmail": "Verify Email",
  "nationalNumber": "National ID",

  "forget_password_question": "Forgot password?",
  "no Account": "Don't have an account? Sign up now",
  "error_required": "This field must not be empty",
  "error_short_input": "Input is too short",
  "error_enter_email": "Please enter your email",
  "error_invalid_email": "Please enter a valid email address",
  "error_enter_password": "Please enter your password",
  "error_password_min_length": "Password must be at least 6 characters long",
  "error_reenter_password": "Please re-enter your password",
  "error_password_mismatch": "Passwords do not match",
  "error_number_max": "Value must be a number less than or equal to 100",
  "error_required_iban": "IBAN is required",
  "error_invalid_iban":
      "Please enter a valid Saudi IBAN starting with SA and 24 digits",
  "error_required_crn": "Please enter the commercial registration number",
  "error_invalid_crn": "CRN must be 10 digits and not start with 0",
  "error_enter_id": "Please enter the identity number",
  "error_id_numbers_only": "Identity number must contain only digits",
  "error_id_max_length": "Identity number must not exceed 10 digits",
  "error_required_account_number": "Account number is required",
  "error_not_zero": "Value must be greater than 0",
  "newPassword": "New Password",
  "passChanged": "Your password has been successfully changed",
  "backToLogin": "Back to Login",
  "addInfo": "Add Your Personal Information",
  "birthday": "Date of Birth",
  "phoneNumber": "Phone Number",
  "national": "Nationality",
  "companyName": "Company Name",
  "companyRecord": "Commercial Registration Number",
  "uniNumber": "Unified Number",
  "activityType": "Activity Type",
  "term": "Terms & Conditions",
  "nafazCheck": "Verify via Nafath",
  "aggrement": "Digital Signature Subscription Agreement",
  "view_agreement": "To view the digital signature agreement ",
  "click_here": "Click here",
  "confirmAggrement": "I agree to the digital signature subscription",
  "confirmCreditAccess":
      "I agree to allow access to my credit information from SIMAH, Bayan, and credit exchange",
  "newAccount": "Create New Account",
  "investorType": "Investor Type",
  "otpCode": "Verification Code",
  "haveAccount": "Already have an account? Log in",
  "individual": "Individual",
  "company": "Company",
  "nafaz": "Nafaz",
  "enter_nafaz_code": "Please enter the code displayed in the Nafaz app",
  "invalid_birth_date":
      "The birthdate is incorrect. Please go back and update it.",
  "missing_individual_address":
      "Please complete your personal address and try again.",
  "missing_company_address":
      "Please complete your company address and try again.",
  "nafaz_failed_title": "Verification Failed",
  "nafaz_failed_desc": "Would you like to resend the code?",
  "yes": "Yes",
  "signature_title": "Signature",
  "investment_agreement_title": "Investment Agreement",
  "investment_agreement_note":
      "Please download and read the full agreement. Then, click sign to digitally sign the agreement and activate your investment account.",
  "view_file": "View File",
  "sign_agreement": "Sign Agreement",
  "fillInfo": "Fill in the required information",
  "save": "Save",
  "onboarding1": "Annual returns up to 17%",
  "onboarding2": "Multiple investment opportunities",
  "onboarding3":
      "Register and invest in real estate projects easily and securely",
  "error_timeout": "Request timed out. Please try again.",
  "error_no_connection":
      "No Internet connection. Please check your connection.",
  "error_http_failure": "HTTP request failed. Please try again.",
  "error_invalid_format": "Invalid response format. Please try again.",
  "error_authentication_required":
      "Authentication is required. Please login first.",
  "error_unexpected": "An unexpected error occurred. Please try again.",
  "investment_portfolio": "Investment Portfolio",
  "wallet_value": "Wallet Value",
  "revenue": "Revenue",
  "revenue_rate": "Revenue Rate",
  "view_more": "View More",
  "partner_in_real_estate": "Your partner in real estate development",
  "start_investment_journey": "Start your investment journey with us",
  "investment_opportunities": "Investment opportunities",
  "total_investments": "Total Investments",
  "bank_account_required": "You must create a bank account to start investing",
  "create_bank_account": "Create Bank Account",
  "مد": "Welcome Back",
  "view_all": "View All",
  "press_back": "Press back",
  "more_times_to_close": "more times to close the app",
  "visitor": "Visitor",
  "invalid_index": "Invalid index",
  "guest_user_message":
      "Sorry, you cannot proceed. Please register first to complete the process.",
  "financing_amount": "Financing Amount",
  "financing_duration": "Financing Duration",
  "months": "months",
  "risk_rating": "Risk Rating",
  "opportunity_return": "Return on Opportunity",
  "annual_profit_rate": "Annual Profit Rate",
  "monthly_profit_rate": "Monthly Profit Rate",
  "company_participation": "Company Participation Rate",
  "no_title": "No title",
  "enter_investment_amount": "Enter investment amount here",
  "invest": "Invest",
  "risk_disclaimer": "Risk Disclaimer",
  "risk_disclaimer_description":
      "I acknowledge that I have read the terms and conditions of the investment agency via the Thara debt crowdfunding platform, and I understand the potential risks, including but not limited to loss of capital, platform suspension, lack of diversification, and all associated investment risks. I understand that investing through the platform carries a high degree of risk and does not guarantee returns. Thara does not guarantee capital protection or assume liability for losses. This investment is not a bank deposit or guaranteed product. I have reviewed the investment opportunity details before making a decision, and I understand that returns will be distributed based on the specified schedule after deducting the agency fees mentioned in the opportunity.",

  // About Us
  "about_us":
      "A fintech company specializing in financing real estate development projects, connecting individual and institutional investors with investment opportunities in the real estate development sector under Murabaha contracts. The aim is to provide liquidity for real estate development projects and returns for funders.",
  "cancel_investment_title": "Cancel Investment",
  "cancel_investment_description":
      "Are you sure you want to cancel the investment? This action cannot be undone.",
  "confirm_cancel_investment": "Confirm Cancellation",
  "no_conflict_of_interest": "No conflict of interest",
  "payment_month": "Payment Month",
  "principal_amount": "Principal Amount",
  "profit": "Profit",
  "platform_fee": "Platform Fee",
  "net_profit": "Net Profit",
  "total": "Total",
  "covered": "Covered",
  "remaining_days": "Remaining",
  "days": "days",
  "minimum_investment": "Minimum investment is",
  "currency_sar": "SAR",
  "owner_cannot_invest": "You cannot invest as you are the opportunity owner",
  "already_subscribed": "You have already invested",
  "cancel_investment": "Cancel Investment",
  "investment_hint": "Enter investment amount here",
  "opportunity_details": "Opportunity Details",
  "about_opportunity": "About Opportunity",
  "payment_schedule": "Payment Schedule",
  "attachments": "Attachments",
  "conflict_of_interest": "Conflict of Interest",
  "other_opportunities": "Other Opportunities",
  "choose_date": "choose date",
  "your_investment_summary": "Your Investment Summary",
  "no_data": "No data available",
  "no_name": "No name",
  "investment_status_pending": "Pending Approval",
  "investment_status_approved": "Approved",
  "investment_status_rejected": "Rejected",
  "investment_status_cancelled": "Cancelled",
  "collected_profits": "Collected Profits",
  "active_investments": "Active Investments",
  "expected_total_profit": "Expected Total Profit",
  "investment_summary": "Your Investment Summary",
  "status_active": "Active",
  "status_closed": "Closed",
  "status_on_hold": "Hold",
  "status_paid": "Paid",
  "status_canceled": "Canceled",
  "status_overdue": "Overdue",
  "status_unknown": "Unknown",
  "your_info": "Your Info",
  "settings": "Settings",
  "contact_us": "Contact Us",
  "others": "Others",
  "personal_info": "Personal Information",
  "kyc_form": "KYC Form",
  "bank_info": "Bank Information",
  "manage_notifications": "Manage Notifications",
  "language": "Language",
  "change_password_pin": "Password & PIN",
  "choose_language": "Choose Language",
  "arabic": "Arabic - العربية",
  "english": "English - الإنجليزية",
  "support_tickets": "Support Tickets",
  "sharia_committee": "Sharia Committee",
  "about us": "About Us",
  "financial_reports": "Financial Reports",
  "faq": "FAQ",
  "articles": "Articles",
  "terms_conditions": "Terms & Conditions",
  "logout": "Logout",
  "beneficiary_name": "Beneficiary Name",
  "iban_number": "IBAN Number",
  "save_changes": "Save Changes",
  "id_number": "ID Number",
  "delete_my_account": "Delete My Account",
  "you_can_reach_us_through": "You can reach us through:",
  "email_us": "Email us",
  "call_us": "Call us",
  "working_hours": "Working Hours",
  "working_hours_text": "Sunday to Thursday, 9:00 AM – 5:00 PM",
  "select_inquiry_type": "Select inquiry type",
  "write_message_here": "Write your message here",
  "message_required": "Message is required",
  "message_max_length": "Message must not exceed 250 characters",
  "send": "Send",
  "year": "Year",
  "quarter": "Quarter",
  "view_report": "Download Report",
  "job_status": "Job Status",
  "government_sector": "Government Sector",
  "private_sector": "Private Sector",
  "businessman": "Businessman",
  "retired": "Retired",
  "unemployed": "Unemployed",
  "student": "Student",
  "notifications": "Notifications",
  "notification_title": "Important Notification",
  "notification_description":
      "Your new investment has been approved. You can now monitor profits from the dashboard.",
  "notification_time_ago": "2 hours ago",

  "terms_conditions_title": "Terms & Conditions",

  "terms_intro": "Introduction",
  "terms_intro_list1":
      "Thara enables you to begin using the platform upon accepting the terms.",
  "terms_intro_list2":
      "Please read the terms carefully before using the platform...",

  "terms_eligibility": "Eligibility Requirements:",
  "terms_eligibility_list1": "You must be 18 years or older...",
  "terms_eligibility_list2": "As an investor, you may be asked to provide...",

  "terms_illegal": "Prohibited Actions:",
  "terms_illegal_list1":
      "Publishing materials from the platform without approval...",
  "terms_illegal_list2": "Selling or sublicensing any content...",
  "terms_illegal_list3": "Displaying materials for commercial use...",
  "terms_illegal_list4": "Reproducing or copying content...",

  "terms_prohibited": "Unauthorized Usage:",
  "terms_prohibited_list1":
      "You may not use the site for illegal or harmful purposes...",
  "terms_prohibited_list2":
      "Spreading malware or bypassing security is prohibited...",

  "terms_fees": "Fees Details:",
  "terms_fees_list1":
      "You agree to pay administrative fees for services provided...",

  "terms_warranty": "Warranties:",
  "terms_warranty_list1":
      "Thara makes no guarantees regarding the accuracy or performance...",

  "terms_liability": "Liability Limits:",
  "terms_liability_list1":
      "Thara is not liable for direct or indirect losses...",
  "terms_liability_list2":
      "No compensation will be paid due to service delays...",

  "terms_conflict_policy": "Conflict of Interest Policy:",
  "terms_conflict_policy_list1":
      "Thara operates transparently, and will disclose conflicts...",

  "terms_dispute": "Governing Law & Disputes:",
  "terms_dispute_list1": "These terms are governed by Saudi laws...",

  "terms_general": "General Provisions:",
  "terms_general_list1": "Thara may change these terms at any time...",
  "terms_general_list2":
      "Delays in enforcing any term will not waive that right...",

  "terms_obligations": "You must not:",
  "terms_obligations_list1":
      "Reproduce or share content beyond permitted use...",
  "terms_obligations_list2":
      "Provide false information or access other accounts...",
  "about_us_title": "About Thara",
  "about_us_slogan": "Your Partner in Real Estate Development",
  "about_us_subtitle": "About Thara Debt-Based Crowdfunding",
  "about_us_description":
      "Thara is a licensed crowdfunding platform offering investment opportunities in the real estate sector through debt-based financing, providing innovative solutions for both investors and developers.",
  "delete_account_title": "Delete Account",
  "delete_account_message":
      "Are you sure you want to permanently delete your account? This action cannot be undone.",
  "delete_account_button": "Delete Account",
  "delete_account_success": "Account deleted successfully",
  "logout_title": "See you soon",
  "logout_message": "Are you sure you want to log out?",
  "logout_button": "Log Out",
  "change_password": "Change Password",
  "old_password": "Old Password",
  "new_password": "New Password",
  "notification_settings": "Notification Settings",
  "email_notifications": "Email Notifications",
  "general_notifications": "General Notifications",
  "new_opportunities": "New Opportunities",
  "full_name": "Full Name",
  "ticket_type": "Ticket Type",
  "description": "Description",
  "send_ticket": "Send Ticket",
  "sharia_title": "Islamic Sharia",
  "sharia_intro":
      "At Thara Debt Crowdfunding Company, we are committed to complying with Islamic Sharia in all our dealings. This is ensured through the appointment and supervision of the Shariyah Review Bureau as the Sharia advisor to provide guidance and ensure alignment with Sharia standards.",
  "sharia_bullet_1":
      "Preparing Sharia standards that the company's management adheres to when investing.",
  "sharia_bullet_2":
      "Reviewing and approving company documents including terms and conditions, subscription agreements, policies, procedures, and other documents necessary for certification.",
  "sharia_bullet_3":
      "Ensuring the platform’s compliance with the committee’s decisions regarding its products and contracts.",
  "sharia_bullet_4":
      "Responding to inquiries from company management regarding its investments or activities.",
  "sharia_bullet_5":
      "Supervising and monitoring the company's activities to ensure compliance with Sharia standards.",
  "sharia_download_label": "View & Download",
  "wallet_status": "upgrade to professional is under review",
  "wallet_upgrade": "upgrade successfully to professional investor",
  "error_password_format":
      "Password must contain at least 1 uppercase, 1 lowercase, and 1 number",
  "Available": "Available Opportunities",
  "Completed": "Completed Opportunities",
  "All": "All Opportunities",

  // new ui
  "login_welcome_title": "Welcome!",
  "login_welcome_subtitle": "Enter your account details to continue",
  "login_email_label": "Email",
  "login_email_hint": "Enter your email address",
  "login_password_label": "Password",
  "login_password_hint": "Enter your password",
  "login_forgot_password": "Forgot Password",
  "login_button": "Login",
  "login_create_account": "Create Account",

  // Register Screen
  "register_title": "Create New Account",
  "register_type": "Register Type",
  "register_email": "Email",
  "register_email_hint": "Enter your email address",
  "register_password": "Password",
  "register_password_hint": "************",
  "register_confirm_password": "Confirm Password",
  "register_confirm_password_hint": "Re-enter your password",
  "register_terms": "I agree to the Privacy Policy and Terms & Conditions",
  "register_submit": "Send Verification Code",

  // Password rules
  "password_rule_uppercase": "Must contain at least one uppercase letter (A-Z)",
  "password_rule_lowercase": "Must contain at least one lowercase letter (a-z)",
  "password_rule_number": "Must contain at least one number (0-9)",
  "password_rule_length": "Must be at least 8 characters long",
  "password_rule_no_spaces": "Must not contain spaces",

  "register_info_title": "Basic Information",
  "register_nationality": "Nationality",
  "register_select_nationality": "Select nationality",
  "register_id": "National ID / Iqama",
  "register_id_hint": "Enter National ID or Iqama number",
  "register_phone": "Phone Number",
  "register_phone_hint": "5xxxxxxxx",
  "register_phone_rule": "Phone number must start with 5",
  "register_birthdate": "Date of Birth",
  "register_birthdate_hint": "Select your birthdate",
  "register_hijri_date": "Hijri Equivalent",
  "register_hijri_hint": "yyyy-mm-dd",
  "register_signature_title": "Digital Signature Agreement",
  "register_signature_terms": "I agree to subscribe using digital signature",
  "next": "Next",
  "done": "Done",
  "gregorian": "gregorian",
  "hijri": "hijri",
  "onboard_title_1": "Ambitious and Continuous Growth",
  "onboard_desc_1":
      "Thara platform delivered an average annual return of 14.44% on executed investments, making it an attractive choice for capital growth.",

  "onboard_title_2": "Security and Trusted Investment",
  "onboard_desc_2":
      "Our platform is licensed by the Saudi Central Bank and operates under its supervision to ensure the highest levels of security and transparency in every financing and investment operation.",

  "onboard_title_3": "Full Commitment in Collection",
  "onboard_desc_3":
      "Thara platform achieved a full 100% collection rate of due amounts, reflecting financial management efficiency and effective collection mechanisms.",

  "finish": "Finish",
  "register_credit_terms":
      "I agree to review my credit information with SIMAH and Bayan and to exchange credit information",

  "forget_password_title": "Reset Password",
  "forget_password_section_title": "Basic Information",
  "email_hint": "Enter your email address",
  "national_id": "National ID / Iqama",
  "national_id_hint": "Enter your National ID or Iqama number",
  "reset_password_title": "Reset Password",
  "password_hint": "************",
  "password_rule_upper": "Contains an uppercase letter (A-Z)",
  "password_rule_lower": "Contains a lowercase letter (a-z)",
  "password_rule_spaces": "Must not contain spaces",
  "confirm_password_hint": "Enter password confirmation",
  "confirm_password_required": "Please confirm your password",
  "passwords_not_match": "Passwords do not match",
  "otp_enter_code": "Enter verification code",
  "otp_sent_email":
      "We have sent a code to your email below to verify your identity",
  "otp_sent_phone":
      "We have sent a code to your phone number below to verify your identity",
  "otp_not_received": "Didn’t receive the code? ",
  "otp_resend_request": "Request resend code",
  "otp_resend_in": "Resend code in @seconds seconds",
  "register_info_basic": "Basic Information",
  "register_info_nationality": "Nationality",
  "register_info_nationality_hint": "Select nationality",
  "register_info_id_label": "National ID / Residency",
  "register_info_id_hint": "Enter National ID or Residency Number",
  "register_info_phone_label": "Mobile Number",
  "register_info_phone_hint": "5xxxxxxxx",
  "register_info_phone_hint_text": "Start the mobile number with 5",
  "register_info_birthdate_label": "Date of Birth",
  "register_info_birthdate_hint": "Select birth date",
  "register_info_hijri_label": "Equivalent Hijri Date",
  "register_info_hijri_hint": "yyyy-mm-dd",
  "register_info_signature_title": "Digital Signature Agreement",
  "register_info_terms": "I agree to subscribe using the digital signature",
  "view": "View",
  "month_january": "January",
  "month_february": "February",
  "month_march": "March",
  "month_april": "April",
  "month_may": "May",
  "month_june": "June",
  "month_july": "July",
  "month_august": "August",
  "month_september": "September",
  "month_october": "October",
  "month_november": "November",
  "month_december": "December",
  "hijri_muharram": "Muharram",
  "hijri_safar": "Safar",
  "hijri_rabi_al_awwal": "Rabi Al-Awwal",
  "hijri_rabi_al_thani": "Rabi Al-Thani",
  "hijri_jumada_al_ula": "Jumada Al-Ula",
  "hijri_jumada_al_thania": "Jumada Al-Thania",
  "hijri_rajab": "Rajab",
  "hijri_shaban": "Sha'ban",
  "hijri_ramadan": "Ramadan",
  "hijri_shawwal": "Shawwal",
  "hijri_dhul_qidah": "Dhul-Qi'dah",
  "hijri_dhul_hijjah": "Dhul-Hijjah",

  "fund_size": "Fund Size",
  "annual_return": "Annual Return",
  "coverage": "Coverage",
  "days_left": "Days Left",
  "day": "day",
  "view_opportunity": "View Opportunity",
  "investment_project": "Investment Project",
  "by_undefined_company": "By an undefined company",
  "one_step_away_from_investment":
      "You are one step away from starting your investment!",
  "please_add_balance_to_start_investment":
      "Please add balance to your wallet to start investing.",
  "add_balance": "Add Balance",
  "view_all_opportunities": "View All Opportunities",
  "your_investment_wallet_balance": "Your Investment Wallet Balance",
  "investment_transactions": "Investment Transactions",
  "filter": "Filter",
  "no_investments_now": "No investments currently",
  "opportunity_name": "Opportunity Name",
  "investment_amount": "Investment Amount",
  "investment_duration": "Investment Duration",
  "investment_date": "Investment Date",
  "expected_profit": "Expected Profit",
  "realized_profit_in_wallet": "Realized Profit in Wallet",
  "status": "Status",
  "filter_investment_transactions": "Filter Investment Transactions",
  "search_in_all_results": "Search text in all results",
  "investment_status": "Investment Status",
  "please_select": "Please Select",
  "start_date_range": "Start Date Range",
  "end_date_range": "End Date Range",
  "cancel_all_filters": "Cancel All Filters",
  "investment_word": "Investment",
  "active_investment_amount_count": "Active Investment Amount Count",
  "active_investment_amounts": "Active Investment Amounts",
  "total_investment_count": "Total Investment Count",
  "total_expected_profit": "Total Expected Profit",
  "total_invested_amount": "Total Invested Amount",
  "total_realized_profit": "Total Realized Profit",
  "monthly_profits": "Monthly Profits",
  "expected_profits": "Expected Profits",
  "realized_profits": "Realized Profits",
  "delayed_profits": "Delayed Profits",
  "no_years_available": "No years available currently",
  "no_valid_investment_dates": "No investments with valid dates were found.",
  "close": "Close",
  "january": "January",
  "february": "February",
  "march": "March",
  "april": "April",
  "may": "May",
  "june": "June",
  "july": "July",
  "august": "August",
  "september": "September",
  "october": "October",
  "november": "November",
  "december": "December",
  "by": "By",
  "fund_goal": "Fund Goal",
  "return_on_investment": "Return on Investment",
  "risk_low": "Low",
  "risk_medium": "Medium",
  "risk_high": "High",
  "start_first_investment": "Start Your First Investment",
  "upgrade_to_qualified_investor": "Upgrade to Qualified Investor",
  "qualified_investor_description":
      "Enjoy additional benefits and exclusive opportunities by upgrading to a qualified investor — available only for experienced and financially capable individuals.",
  "activate_qualified_investor_benefits":
      "Activate Your Qualified Investor Benefits Today",
  "upgrade_request_under_review": "Upgrade Request Under Review",
  "upgrade_request_review_description":
      "Your request to upgrade to a qualified investor has been received and is currently under review by our team. You will be notified once approved or if additional documents are required.",
  "qualified_investor": "Qualified Investor",
  "qualified_investor_approved_description":
      "Your upgrade to Qualified Investor has been approved! You can now enjoy exclusive investment opportunities and additional benefits within the platform.",
  "all_investment_opportunities": "All Investment Opportunities",
  "home": "Home",
  "no_opportunities_available": "No opportunities at the moment",
  "new_opportunities_soon":
      "New opportunities will be displayed once available.",
  "opportunities": "Opportunities",
  "wallet": "Wallet",
  "available_opportunities": "Available ",
  "upcoming_opportunities": "Upcoming ",
  "completed_opportunities": "Completed ",
  "discover_investment_opportunity":
      "Discover this unique investment opportunity:",
  "project_code": "Project Code:",
  "share_via_tharaa": "Share via Thara App!",
  "fund_duration": "Funding Duration",
  "month": "Month",
  "distributions": "Distributions",
  "quarterly": "Quarterly",
  "payment_number": "Payment",
  "due_date": "Due Date",
  "interest": "Interest",
  "taxes_and_fees": "Taxes & Fees",
  "total_payment": "Total Payment",
  "first": "First",
  "second": "Second",
  "third": "Third",
  "fourth": "Fourth",
  "fifth": "Fifth",
  "sixth": "Sixth",
  "seventh": "Seventh",
  "eighth": "Eighth",
  "ninth": "Ninth",
  "tenth": "Tenth",
  "investment_agreement": "Investment Agreement",
  "investment_agreement_description":
      "Please download the agreement file and review all its terms, then press the 'Sign' button to sign the agreement and activate your investment account.",
  "download": "Download",
  "disclosures": "Disclosures",
  "withdraw_investment": "Withdraw Investment",
  "withdraw_investment_confirmation":
      "You are about to withdraw your investment. Are you sure you want to proceed?",
  "owner_investment_restriction":
      "The owner cannot invest in an opportunity they own.",
  "already_invested_title": "You are already invested in this opportunity",
  "already_invested_description":
      "You have already invested in this opportunity.",
  "riyal": "SAR",
  "info": "Info",
  "success": "Success",
  "investment_operations": "Investment Operations",
  "no_deposit_operations": "No deposit operations yet",
  "no_withdraw_operations": "No withdrawal operations yet",
  "date_range": "Date Range",
  "until": "until",
  "search": "Search",
  "bank_account": "Bank Account",
  "investment_account_prefix": "Investment Account -",
  "transaction_amount": "Transaction Amount",
  "transaction_date": "Transaction Date",
  "complete_verification": "Complete Verification",
  "cancel_withdrawal_title": "Cancel Withdrawal",
  "cancel_withdrawal_body":
      "The withdrawal will be canceled. Do you wish to proceed?",
  "cancel_withdrawal_confirm": "Confirm Withdrawal Cancellation",
  "investment_account": "Investment Account",
  "unknown_source": "Unknown Source",
  "withdraw_from_balance": "Withdraw from balance",
  "transfer_amount": "Transfer amount",
  "transfer_to": "Transfer to",
  "select_bank_account": "Select bank account",
  "total_transfer_fees": "Total transfer fees",
  "total_deducted_amount": "Total deducted amount",
  "upgrade_instructions":
      "To upgrade your account, choose at least one of the following requirements and attach supporting documents.",
  "requirement_annual_income":
      "Annual income or profits not less than 600,000 SAR in the last two years.",
  "requirement_net_assets":
      "Total personal assets not less than 3 million SAR.",
  "requirement_experience":
      "At least 3 years of work experience in the financial sector or a professional investment-related role.",
  "requirement_certification":
      "A recognized professional certification related to finance or investment.",
  "submit": "Submit",
  "select_at_least_one_requirement":
      "Please select at least one requirement and upload its documents.",
  "upload_required_documents":
      "Please upload documents for the selected requirements.",
  "filter_deposit_history": "Filter Deposit History",
  "filter_withdraw_history": "Filter Withdraw History",
  "search_in_results": "Search text in all results",
  "select_request_status": "Please select request status",
  "select_money_transfer_status": "Please select money transfer status",
  "approved": "Approved",
  "rejected": "Rejected",
  "available_balance": "Available Balance",
  "trusted_bank_accounts": "Trusted Bank Accounts",
  "unknown": "Unknown",
  "arab_bank": "Arab Bank",
  "iban_copied": "IBAN copied successfully",
  "account_copied": "Account number copied successfully",
  "choose_payment_method": "Choose a payment method",
  "credit_or_debit_card": "Credit/Debit Card",
  "bank_card": "Bank Card",
  "deposit_method_selected": "Deposit method selected",
  "cardholder_name": "Cardholder Name",
  "card_number": "Card Number",
  "expiry_date": "Expiry Date",
  "month_year": "MM/YY",
  "cvv_code": "CVV",
  "save_card_for_future": "Save card for future payments",
  "primary_account": "Primary Account",
  "alternate_account_name": "Alternate Account Name",
  "account_owner_name": "Account Holder Name",
  "transfer_note_title": "Note Before Transfer",
  "transfer_note_description":
      "Please ensure that the transfer is made from an account previously added in Tharaa.",
  "total_surplus_balance": "Total Surplus Balance",
  "add_balance_button": "Add Balance",
  "withdraw_available_balance": "Withdraw Available Balance",
  "attach_account_ownership_proof": "Please attach proof of account ownership",
  "upload_account_proof_description":
      "Please attach a document proving your bank account ownership in PDF or image format (PNG, JPG) with a size not exceeding 5 MB.",
  "select_national_address": "Select National Address",
  "address_type": "Address Type",
  "primary": "Primary",
  "secondary": "Secondary",
  "add_account": "Add Account",
  "add_bank_account_info": "Add Your Bank Account Information",
  "add_bank_account_subtitle":
      "You must add your bank account before transferring any balance to your wallet. No funds will be withdrawn from your account. This process ensures your bank details are saved for transferring investments or profits and for matching incoming transfers.",
  "enter_account_alias_hint": "Enter an account alias (e.g., Savings Account)",
  "select_bank_hint": "Please select a bank",
  "bank_account_number": "Bank Account Number",
  "enter_bank_account_hint": "Enter your bank account number",
  "enter_iban_hint": "Enter your IBAN number",
  "profile_title": "Profile",
  "account_settings": "Account Settings",
  "language_option": "English",
  "account_and_settings": "Account & Settings",
  "face_id_login": "Login with Face ID",
  "help_and_support": "Help & Support",
  "raise_ticket": "Raise a Ticket",
  "call": "Call",
  "message": "Message",
  "call_failed": "Couldn't make the call",
  "email_failed": "Couldn't open mail app",
  "about_thara": "About Thara",
  "islamic_compliance": "Shariah Compliance",
  "credit_rating": "Credit Rating",
  "visit_website": "Visit Thara Website",
  "license_note":
      "“Thara for Debt Crowdfunding” is a licensed entity under the supervision of the Saudi Central Bank. License No. (84/A Sh/202401). © 2025 All rights reserved.",
  "about_paragraph":
      "A fintech company specializing in real estate development project financing, connecting investors with opportunities through Murabaha contracts to provide liquidity and returns.",
  "app_version": "App Version v1.3.09",
  "investment_account_status": "Investment Account Status",
  "account_type": "Account Type",
  "loan_account_status": "Loan Account Status",
  "upgrade_request_pending": "Upgrade request pending review",
  "already_professional_investor": "You are already a qualified investor",
  "upgrade_to_professional_investor": "Upgrade to Qualified Investor",
  "disable_account": "Disable Account",
  "name_in_english": "Name in English",
  "account_owner": "Account Owner",
  "national_id_or_residence": "National ID / Residency",
  "birth_date_gregorian": "Date of Birth (Gregorian)",
  "mobile_number": "Mobile Number",
  "email_address": "Email Address",
  "edit": "Edit",
  "company_name": "Company Name",
  "company_field": "Field of Business",
  "commercial_registration": "Commercial Registration Number",
  "unified_number": "Unified Number",
  "edit_email_title": "Edit Email Address",
  "new_email_label": "New Email Address",
  "new_email_hint": "Enter your new email address",
  "invalid_email_error": "Please enter a valid email address",
  "edit_phone_number": "Edit Phone Number",
  "new_phone_number": "New Phone Number",
  "enter_new_phone_number": "Enter your new phone number",
  "enter_valid_phone": "Please enter a valid phone number",
  "verify_email_title":
      "Enter the verification code sent to your current email",
  "verify_email_desc":
      "We have sent a code to your current email address to verify your identity",
  "verify_email_check_spam": "Check your spam folder or ",
  "resend_in": "Resend in {{seconds}}",
  "code_resent_success": "Verification code resent successfully",
  "enter_otp_for_new_phone":
      "Enter the verification code sent to your new phone number",
  "otp_sent_to_phone": "We sent a code to your phone for verification",
  "did_not_receive_code": "Didn't receive the code? ",
  "resend_in_seconds": "Resend in {{seconds}} seconds",
  "notify_new_projects":
      "Alert when new investment projects are launched on the platform",
  "notify_financial_operations": "Financial operations (Deposit & Withdraw)",
  "notify_profit_added": "Alert when profits are added to your balance",
  "notify_portfolio_performance":
      "Notifications for portfolio and investment performance updates",
  "notify_articles_materials":
      "Notification when new articles or educational materials are available",
  "notify_updates_announcements":
      "Alert for the latest updates and announcements from Thara",
  "disable_all_notifications": "Disable all notifications",
  "new_ticket": "New Ticket",
  "working_hours_notice":
      "Dear customer,\nPlease note that working hours are from Sunday to Thursday, 09:00 AM to 05:00 PM.",
  "enter_full_name": "Enter your full name",
  "enter_phone_number": "Enter your phone number",
  "select_ticket_type": "Select ticket type",
  "write_message": "Write your message",
  "user_name_placeholder": "User Name",
  "current_password": "Current Password",
  "confirm_new_password": "Confirm New Password",
  "confirm_change_password": "Confirm Password Change",
  "rule_uppercase": "Contains at least one uppercase letter (A-Z)",
  "rule_lowercase": "Contains at least one lowercase letter (a-z)",
  "rule_number": "Contains at least one number (0-9)",
  "rule_no_spaces": "Does not contain spaces",
  "rule_min_length": "Minimum length of 12 characters",
  "logout_description": "Are you sure you want to log out of your account?",
  "confirm_logout": "Confirm Logout",
  "logout_success": "You have successfully logged out",
  "about_thara_title": "About Thara",
  "thara_company_name": "Thara Financing Company",
  "thara_vision_summary":
      "Our vision is to be the leading destination for innovative investment financing in the Kingdom.",
  "our_vision": "Our Vision",
  "vision_description":
      "To be the trusted financial partner that leads the future of investment financing through innovation, technology, and confidence.",
  "our_mission": "Our Mission",
  "mission_description":
      "To provide safe and Sharia-compliant financing and investment solutions that support startups and contribute to the development of the national economy.",
  "contact_info":
      "Email: info@tharaco.sa\nPhone: 8001240393\nWebsite: www.thara.sa",
  "all_rights_reserved": "All rights reserved.",
  "terms_intro_text":
      "Learn about Thara Platform’s terms and conditions of service.",
  "terms_footer_text":
      "Thara Finance affirms its full commitment to transparency and user protection.",
  "terms_intro_title": "Introduction",
  "terms_eligibility_title": "Eligibility",
  "terms_illegal_title": "Illegal Activities",
  "terms_prohibited_title": "Prohibited Activities",
  "terms_fees_title": "Fees & Charges",
  "terms_warranty_title": "Warranties",
  "terms_liability_title": "Liabilities",
  "terms_conflict_title": "Conflict of Interest Policy",
  "terms_dispute_title": "Dispute Resolution",
  "terms_general_title": "General Provisions",
  "terms_obligations_title": "User Obligations",

  "sharia_compliance_title": "Shariah Compliance",
  "sharia_committee_title": "Sharia Supervisory Committee",
  "sharia_committee_desc":
      "The Sharia Supervisory Committee ensures that all Thara’s financial and investment products comply with Islamic law through thorough review and auditing.",
  "sharia_point1": "Oversees all financing products for compliance.",
  "sharia_point2": "Reviews contracts to ensure Sharia compliance.",
  "sharia_point3": "Issues annual Sharia compliance reports.",
  "sharia_point4": "Monitors the implementation of Fatwas in operations.",
  "sharia_point5": "Approves investor-related contracts and policies.",
  "sharia_certificate_title": "Sharia Accreditation Certificate",
  "sharia_certificate_desc":
      "You can view and download the official Sharia accreditation certificate issued by the committee.",
  "download_certificate": "Download Certificate",
  "sharia_footer_note":
      "Thara Finance – All products are Sharia-compliant under the supervision of the Sharia Committee.",

  "financial_reports_title": "Financial Reports",
  "no_financial_reports": "No financial reports available at the moment",
  "financial_reports_header":
      "Browse and view Thara’s quarterly and annual financial reports.",
  "financial_year": "Fiscal Year ",
  "financial_report_description":
      "You can download the financial report to review the company’s financial performance during this period.",
  "download_report": "Download Report",
  "no_file_available": "No file available for download",
  "transfer_source": "Transfer Source",
  "active_status": "Active",
  "account_deleted_success": "Account has been successfully deleted",
  "account_type_company": "Company Account",
  "account_type_individual": "Individual Account",
  "account_type_unknown": "Not specified",
  "status_inactive": "Inactive",
  "status_not_activated": "Not activated",
  "status_pending": "Pending",
  "status_not_applied": "Not applied",
  "investor_professional": "Qualified Investor",
  "investor_upgrade_pending": "Upgrade Request Under Review",
  "investor_upgrade_request": "Investor Upgrade Request",
  "investor_unverified": "Unverified",
  "investor_verified": "Verified Investor",
  "indicator": "Real Estate Indicator",
  "login_guest": "Login as guest",
  "password_rule_special_char":
      "Contains at least one special character (!@#\$%^&*)",
  "nafath": "Nafath",
  "un_auth": "Session expired, please log in again",
  "notYet": "Not Yet",
  "investment_limit": "Investment Limit",
  "profit_expected": "Expected Profits",
  "profit_gained": "Collected Profits",
  "profit_delayed": "Late Profits",
  "profit_default": "Default Profits",
  "min_required": "Minimum investment amount is required.",
  "value_invalid": "Invalid value.",
  "value_must_be_positive": "The value must be greater than 0.",
  "min_must_be_1000_or_more": "Minimum amount must be 1000 or more.",
  "max_required": "Maximum investment amount is required.",
  "must_be_multiple_of_1000": "The amount must be 1000 or multiples of it.",
  "max_must_be_more_than_min":
      "The maximum value must be greater than or equal to the minimum (@min).",
  "min_invest_title": "Minimum investment amount",
  "max_invest_title": "Maximum investment amount",
  "auto_invest_created_success":
      "Your auto-investment has been set up successfully!",
  "auto_invest_updated_success":
      "Your auto-investment settings have been updated successfully!",
  "auto_invest_edit_anytime":
      "You can modify your preferences anytime from the dashboard.",
  "redirecting_now": "You will be redirected now.",
  "auto_invest_title": "Auto Investment",
  "auto_invest_enabled_now": "Auto-invest is currently active.",
  "edit_auto_invest_settings": "Edit Settings",
  "stop_auto_invest": "Stop Auto Investment",
  "auto_invest_title_header": "Automated Investing by Thara",
  "auto_invest_subtitle": "Invest smartly, let us handle the execution!",

  "auto_invest_feature_simple": "Effortless",
  "auto_invest_feature_simple_desc":
      "Just set your preferences and the system will automatically invest your money in the opportunities that fit you.",

  "auto_invest_feature_control": "Full Control",
  "auto_invest_feature_control_desc":
      "Choose the amount, risk level, duration, and update anything anytime.",

  "auto_invest_feature_tracking": "Smooth Monitoring",
  "auto_invest_feature_tracking_desc":
      "Monitor your investment performance anytime from a unified dashboard.",

  "auto_invest_feature_flexibility": "Flexible Stop",
  "auto_invest_feature_flexibility_desc":
      "Stop your automated investment at any moment with one tap.",

  "auto_invest_feature_free": "No Extra Fees",
  "auto_invest_feature_free_desc":
      "The automated advisor service is completely free for you.",

  "risk_level": "Risk Level",
  "risk_level_consent":
      "By clicking, you agree to the risk disclosure statement.",

  "activate_auto_invest": "Activate Automated Investing",

  "real_estate_title": "Real Estate",
  "invoice_title": "Invoices",

  "package_a_desc": "Conservative package with returns of 10% - 13% annually",
  "package_b_desc": "Balanced package with returns of 14% - 16% annually",
  "package_c_desc": "Growth package with returns of 16% - 18% annually",

  "duration_6": "Up to 6 months",
  "duration_12": "12 months",
  "duration_18": "More than 12 months",

  "error_select_opportunity": "You must select at least one opportunity.",
  "error_min_greater_zero": "Minimum amount must be greater than 0.",
  "error_max_greater_zero": "Maximum amount must be greater than 0.",
  "error_max_less_min":
      "Maximum amount must be greater than or equal to minimum.",
  "error_amount_must_1000": "Amount must be 1000 or multiples of it.",
  "error_select_package": "Please select at least one package.",
  "error_select_duration": "Please select an investment duration.",
  "error_general": "An error occurred while saving the settings.",

  "success_edit": "Your investment settings were updated successfully!",
  "success_create": "Your automated investment has been set up successfully!",
  "edit_auto_invest_preferences": "Edit Auto-Invest Preferences",
  "wizard_title": "Auto Investment",
  "wizard_step_0": "Choose Opportunity Type",
  "wizard_step_1": "Set Investment Amount",
  "wizard_step_2": "Choose Package",
  "wizard_step_3": "Choose Duration",

  "wizard_subtitle_multi_select": "You can select multiple options",
  "biometric_title": "Sign in with a glance!",
  "biometric_subtitle":
      "Use Face ID instead of your password. More secure and easier to use.",
  "biometric_skip": "Not now",
  "biometric_enable": "Enable Face ID",
  "about": "About Opportunity",
  "theme": "Theme",
  "light_mode": "Light Mode",
  "dark_mode": "Dark Mode",
  "browse_faq":
      "Browse the most frequently asked questions and their answers about the platform and its services.",
  "error_required_field": "This field is required",
  "error_required_phone": "Please enter phone number",
  "error_invalid_saudi_phone":
      "Phone number must start with 5 and contain 9 digits",
  "enter_amount": "Enter amount",
  "payment": "Payment",
  "total_amount": "Total amount",
  "preparing_payment": "Preparing payment...",
  "payment_init_failed": "Failed to initialize payment",
  "success_account": "Your account has been created successfully! You can now log in and enjoy our services."
};
