include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - "**/*.g.dart"

linter:
  rules:
    # 🔥 Code Quality
    avoid_print: true
    avoid_unnecessary_containers: true
    avoid_empty_else: true
    avoid_redundant_argument_values: true

    # 🔥 Style
    prefer_single_quotes: true
    always_declare_return_types: true
    sort_constructors_first: true
    sort_pub_dependencies: true

    # 🔥 Safety
    cancel_subscriptions: true
    close_sinks: true
    use_build_context_synchronously: true

    # 🔥 Flutter Best Practices
    use_key_in_widget_constructors: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true

    # 🔥 Readability
    lines_longer_than_80_chars: false
    cascade_invocations: true