name: thara
description: "phentic app"
publish_to: 'none'

version: 15.0.0+9

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Core
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  dartz: ^0.10.1
  equatable: ^2.0.5
  http: ^1.2.1
  crypto: ^3.0.3
  uuid: ^4.4.0
  path: ^1.9.0
  intl: ^0.20.2
  shared_preferences: ^2.2.3

  # UI / Design
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.3
  shimmer: ^3.0.0
  font_awesome_flutter: ^10.7.0
  flutter_easyloading: ^3.0.5
  lottie: ^3.1.0
  dotted_border: ^2.1.0
  visibility_detector: ^0.4.0+2
  get_storage: ^2.1.1

  # Media & Files
  image_picker: ^0.8.5+3
  file_picker: ^8.0.7
  open_file: ^3.5.10
  video_player: ^2.10.0
  cached_network_image: ^3.3.1
  share_plus: ^10.0.2
  path_provider: ^2.1.5

  # Permissions & Security
  permission_handler: ^11.3.0
  flutter_secure_storage: ^9.2.4
  local_auth: ^2.3.0

  # UI Widgets / Inputs
  smooth_page_indicator: ^1.2.1
  pin_code_fields: ^8.0.1
  expansion_tile_card: ^3.0.0
  sms_autofill: ^2.3.0
  intl_phone_field: ^3.2.0
  keyboard_actions: ^4.2.0

  # PDF / Web / HTML
  syncfusion_flutter_pdfviewer: ^31.1.19
  webview_flutter: ^4.7.0

  # Time / Date
  hijri: ^3.0.0
  hijriyah_indonesia: ^0.1.2

  # Encryption
  encrypt: ^5.0.1

  # Charts
  syncfusion_flutter_charts: ^31.1.19

  # System / Device
  device_info_plus: ^12.1.0
  flutter_plugin_android_lifecycle: ^2.0.20
  win32: ^5.5.0

  # Networking / APIs
  url_launcher: ^6.3.1
  moyasar: ^2.1.3
  dio: ^5.9.2
  flutter_widget_from_html: ^0.17.1

  # Firebase
  firebase_analytics: ^12.2.0
  firebase_crashlytics: ^5.1.0
  flutter_jailbreak_detection: ^1.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 🔥 أهم إضافة للتست
  integration_test:
    sdk: flutter

  flutter_lints: ^3.0.2

  # Testing
  mocktail: ^1.0.4
  fake_async: ^1.3.1

  # Code generation
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

  # Splash
  flutter_native_splash: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/register_basic_info.pdf
    - assets/RiskStatement_AutomatedInvesting.pdf
    - assets/sharia.pdf

  fonts:
    - family: MyriadArabic
      fonts:
        - asset: assets/fonts/MyriadArabicBold.otf
          weight: 700
        - asset: assets/fonts/MyriadArabicRegular.otf
          weight: 400
        - asset: assets/fonts/MyriadArabicSemibold.otf
          weight: 600
        - asset: assets/fonts/MyriadArabicIt.otf
          weight: 500

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png

  android: true
  ios: true

  android_12:
    color: "#FFFFFF"
    image: assets/images/splash.png
    icon_background_color: "#FFFFFF"

  ios_content_mode: center